import { useLiveData } from "../../hooks/use-live-data";
import { humanizeCode, formatBloodType, formatManilaDateTime, statusClassName } from "../../components/ui/display";
import { InformationHelp } from "../../components/ui/information-help";
import { RefreshButton } from "../../components/ui/refresh-button";
import {canAct} from "../../auth/permissions";
import {V2_BLOOD_TYPES,V2_COMPONENT_TYPES} from "../../services/api/v2";
import type { Principal } from "../../auth/permissions";
import { BankRecordDetails } from "./bank-record-details";
import { BankRecordActions } from "./bank-record-actions";
import { PrcSupplyRequestForm } from "./prc-supply-request-form";
import { V2Operations } from "./v2-operations";
import { componentLabel, facilityLabel } from "./requester-transfer-data";
import { useEffect,useRef,useState } from "react";
import { V2RecordExplorer } from "../inventory/v2-record-explorer";
import { selectionFromSearch, type RecordSelection } from "../../services/api/v2-navigation";
type Request = { transfer_id: string; destination_institution_id: string; blood_type: string; component_type: string; quantity: number; status: string; ledger_transaction_id: string | null };
type Reservation = { reservation_id: string; transfer_id: string | null; local_release_id?: string | null; purpose: string; status: string; version: number };
type Event = { command_id: string; resource_id: string; operation: string; status: string; accepted_at: string; ledger_transaction_id: string | null; block_number: string | null; validation_status: string | null };
export function V2TransferEvidenceView({ principal }: { principal: Principal }) {
  const initial=selectionFromSearch(location.search);
  const [prcFormOpen,setPrcFormOpen]=useState(false);
  const [selected,setSelected]=useState<RecordSelection|undefined>(initial);
  const [tab,setTab]=useState<"requests"|"transfers"|"prc">(initial?.kind==="reservation"?"transfers":"requests");
  const queryParams=new URLSearchParams(location.search);
  const mayRequest=principal.accountId?canAct(principal,"transfer:request"):principal.roleId==="ROLE-03";
  const [formOpen,setFormOpen]=useState(mayRequest&&queryParams.get("newRequest")==="1");
  const formArea=useRef<HTMLDivElement>(null);
  const initialBloodType=V2_BLOOD_TYPES.find(value=>value===queryParams.get("bloodType")),initialComponentType=V2_COMPONENT_TYPES.find(value=>value===queryParams.get("componentType"));
  function scrollToForm(){formArea.current?.scrollIntoView({behavior:matchMedia("(prefers-reduced-motion: reduce)").matches?"auto":"smooth",block:"start"});}
  useEffect(()=>{if(formOpen){const frame=requestAnimationFrame(scrollToForm);return()=>cancelAnimationFrame(frame);}},[formOpen]);
  const [search,setSearch]=useState(""),[status,setStatus]=useState("ALL");
  const state=useLiveData<{requests:Request[];reservations:Reservation[];timeline:Event[];scope?:string;transferSummary?:{status:string;transfer_count:number;unit_count:number}[]}>("/api/v2/transfers");
  const requests=state.data?.requests??[],reservations=state.data?.reservations??[];
  const query=search.trim().toLowerCase();
  const statuses=[...new Set((tab==="requests"?requests:reservations).map(row=>row.status))];
  const shownRequests=requests.filter(row=>(status==="ALL"||row.status===status)&&[row.transfer_id,row.destination_institution_id,row.blood_type,row.component_type,row.status,row.ledger_transaction_id??""].some(value=>value.toLowerCase().includes(query)));
  const shownReservations=reservations.filter(row=>(status==="ALL"||row.status===status)&&[row.reservation_id,row.transfer_id??"",row.local_release_id??"",row.purpose,row.status].some(value=>value.toLowerCase().includes(query)));
  function changeTab(next:"requests"|"transfers"|"prc"){setTab(next);setPrcFormOpen(false);setSelected(undefined);setSearch("");setStatus("ALL");}
  return <div className="blood-bank-transfers">
    <div className="bank-page-toolbar"><div className="requester-transfer-tabs" role="tablist" aria-label="Request and transfer records"><button role="tab" id="bank-requests-tab" aria-controls="bank-records" aria-selected={tab==="requests"} onClick={()=>changeTab("requests")}>Blood Requests <span>{state.data?requests.length:"—"}</span></button><button role="tab" id="bank-transfers-tab" aria-controls="bank-records" aria-selected={tab==="transfers"} onClick={()=>changeTab("transfers")}>Transfers <span>{state.data?reservations.length:"—"}</span></button>{principal.accountCategory==="BLOOD_BANK"&&<button role="tab" id="bank-prc-tab" aria-controls="bank-records" aria-selected={tab==="prc"} onClick={()=>changeTab("prc")}>PRC Supply Requests <span>—</span></button>}</div><div className="bank-toolbar-actions"><RefreshButton busy={state.busy} onRefresh={state.manual}/>{mayRequest&&<button className="button primary compact" onClick={()=>{if(formOpen)scrollToForm();else setFormOpen(true);}}>+ New Blood Request</button>}</div></div>
    <section className="requester-workflow bank-supplier-workflow"><div className="requester-workflow-copy"><span>Current facility workflow</span><strong>Supplier workflow</strong></div><ol>{[["Review Request","Check requirements"],["Approve Request","Verify allocation"],["Prepare Transfer","Prepare reserved units"],["Outbound Scan","Record custody handover"]].map(([stage,hint],index)=><li key={stage}><span>{index+1}</span><div><strong>{stage}</strong><small>{hint}</small></div></li>)}</ol><InformationHelp label="Current facility workflow">As a supplying blood bank, review the request and its requirements, verify stock and operator authority, prepare the allocation, then release units through the approved custody workflow. A blood bank can also request supply from another bank. Request creation is supported; allocation, dispatch and other decision controls remain unavailable here until connected to their verified commands.</InformationHelp></section>
    {state.error&&<div className="requester-transfer-notice" role="status"><span className="requester-notice-icon" aria-hidden="true">!</span><div className="requester-notice-copy"><strong>Records could not refresh</strong><p>{state.error}</p>{state.data&&<p>Showing the last successfully loaded records.</p>}</div><button className="button compact dashboard-refresh" onClick={state.manual}>Retry records</button></div>}
    <div className="bank-record-layout">
      <section className="bank-record-card" role="tabpanel" id="bank-records" aria-labelledby={tab==="requests"?"bank-requests-tab":tab==="prc"?"bank-prc-tab":"bank-transfers-tab"}>
        <header className="bank-section-heading"><h2>{tab==="requests"?"Blood Requests":tab==="prc"?"PRC Supply Requests":"Transfers"}</h2><InformationHelp label={tab==="requests"?"Blood Requests":tab==="prc"?"PRC Supply Requests":"Transfers"}>{tab==="prc"?"Request replenishment through the PRC coordination channel. Supply records and submission will become available when the verified service is connected.":tab==="requests"?"Review recorded requests available to your facility. Select a request to inspect its product, destination and state. A request without a ledger reference is awaiting confirmation; it is not an approval.":"Review transfer and local-release reservations separately from request states. Select a reservation to inspect its workflow and linked components. Preparation, dispatch and receipt controls are not connected here yet."}</InformationHelp></header>
        {tab!=="prc"&&<div className="bank-list-filters"><label className="bank-search">Search {tab==="requests"?"requests":"transfers"}<input type="search" placeholder="Reference or status…" value={search} onChange={event=>setSearch(event.target.value)}/></label><label>Status<span className="requester-select"><select value={status} onChange={event=>setStatus(event.target.value)}><option value="ALL">All statuses</option>{statuses.map(value=><option key={value} value={value}>{humanizeCode(value)}</option>)}</select></span></label></div>}
        {tab==="prc"?<><div className="bank-prc-channel"><div><strong>Philippine Red Cross – Lipa City Chapter</strong><span>Upstream blood supply coordination</span></div><button className="button primary compact" onClick={()=>setPrcFormOpen(value=>!value)}>+ Request PRC Supply</button></div>{prcFormOpen&&<PrcSupplyRequestForm onClose={()=>setPrcFormOpen(false)}/>}<div className="requester-records-empty"><strong>No PRC supply records available</strong><span>PRC supply requests will appear when the coordination read service is connected.</span></div></>:!state.data?<div className="requester-records-empty"><strong>{state.error?"Records unavailable":"Loading records…"}</strong><span>{state.error?"Use Refresh to try again.":"Waiting for your facility’s recorded information."}</span></div>:tab==="requests"?<>
          {state.data.scope==="CITY_AGGREGATE"&&<div className="table-wrap"><table className="data-table"><thead><tr><th>Request state</th><th>Requests</th><th>Units</th></tr></thead><tbody>{state.data.transferSummary?.map(row=><tr key={row.status}><td>{humanizeCode(row.status)}</td><td>{row.transfer_count}</td><td>{row.unit_count}</td></tr>)}</tbody></table></div>}
          {shownRequests.length?<div className="table-wrap"><table className="data-table bank-blood-requests-table"><thead><tr><th>Request ID</th><th>Blood Type</th><th>Component</th><th>Units</th><th>Destination</th><th>Status</th></tr></thead><tbody>{shownRequests.map(row=><tr key={row.transfer_id} onClick={()=>setSelected({kind:"request",id:row.transfer_id})} className={selected?.id===row.transfer_id?"selected":""}><td><button className="requester-record-link mono" aria-label={"Open request "+row.transfer_id} onClick={()=>setSelected({kind:"request",id:row.transfer_id})}>{row.transfer_id}</button></td><td><span className="bank-request-blood-type">{formatBloodType(row.blood_type)}</span></td><td>{componentLabel(row.component_type)}</td><td>{row.quantity}</td><td>{facilityLabel(row.destination_institution_id,principal)}</td><td><span className={statusClassName(row.status)}>{humanizeCode(row.status)}</span>{!row.ledger_transaction_id&&<small className="v2-secondary-id">Awaiting ledger confirmation</small>}</td></tr>)}</tbody></table></div>:<div className="requester-records-empty"><strong>{requests.length?"No requests match your filters":"No blood requests recorded"}</strong><span>{requests.length?"Try another status or search.":"Requests available to your facility will appear here."}</span></div>}
        </>:shownReservations.length?<div className="table-wrap"><table className="data-table"><thead><tr><th>Reservation ID</th><th>Workflow reference</th><th>Purpose</th><th>Status</th></tr></thead><tbody>{shownReservations.map(row=><tr key={row.reservation_id} onClick={()=>setSelected({kind:"reservation",id:row.reservation_id})} className={selected?.id===row.reservation_id?"selected":""}><td><button className="requester-record-link mono" aria-label={"Open reservation "+row.reservation_id} onClick={()=>setSelected({kind:"reservation",id:row.reservation_id})}>{row.reservation_id}</button></td><td className="mono">{row.transfer_id??row.local_release_id??"Unavailable"}</td><td>{humanizeCode(row.purpose)}</td><td><span className={statusClassName(row.status)}>{humanizeCode(row.status)}</span><small className="v2-secondary-id">Version {row.version}</small></td></tr>)}</tbody></table></div>:<div className="requester-records-empty"><strong>{reservations.length?"No transfers match your filters":"No transfer reservations recorded"}</strong><span>{reservations.length?"Try another status or search.":"Transfer and local-release reservations will appear here."}</span></div>}
      </section>
      <aside className="bank-detail-card">{selected?<V2RecordExplorer inline key={selected.kind+selected.id} initial={selected} principal={principal} onClose={()=>setSelected(undefined)} onRefresh={state.manual} renderBody={(record,open)=><BankRecordDetails record={record} principal={principal} open={open}/>} renderExtra={(record,open)=><BankRecordActions record={record} principal={principal} reservations={reservations} open={open}/>} headerHelp={<InformationHelp label="Record details">Review the current authorized record, linked components and ledger evidence. Pending commands and confirmed inventory or custody states remain separate.</InformationHelp>}/>:<><header className="bank-section-heading"><h2>{tab==="requests"?"Request details":tab==="prc"?"PRC supply details":"Transfer details"}</h2><InformationHelp label="Record details">Select a record from the list to inspect its current state and permitted links. Details are read again when opened.</InformationHelp></header><div className="requester-records-empty"><strong>Select a {tab==="requests"||tab==="prc"?"request":"transfer"}</strong><span>Its details will appear here.</span></div></>}</aside>
    </div>
    <div ref={formArea} className="bank-request-form-anchor"><V2Operations principal={principal} onRefresh={state.manual} showRequest={formOpen} onCancelRequest={()=>setFormOpen(false)} initialBloodType={initialBloodType} initialComponentType={initialComponentType}/></div>
    {state.data&&<details className="bank-operation-history"><summary>Recorded operations <span>{state.data.timeline.length}</span></summary><div className="table-wrap"><table className="data-table"><thead><tr><th>Operation</th><th>Command state</th><th>Recorded time</th><th>Ledger reference</th><th>Block / validation</th></tr></thead><tbody>{state.data.timeline.map(event=><tr key={event.command_id}><td>{humanizeCode(event.operation)}</td><td><span className={statusClassName(event.status)}>{humanizeCode(event.status)}</span></td><td>{formatManilaDateTime(event.accepted_at)}</td><td className="mono bank-reference">{event.ledger_transaction_id??"Pending — no commitment"}</td><td>{event.block_number??"—"} / {event.validation_status??"Unverified"}</td></tr>)}{state.data.timeline.length===0&&<tr><td colSpan={5}>No operations recorded.</td></tr>}</tbody></table></div></details>}
  </div>;
}
