import { useLiveData } from "../../hooks/use-live-data";
import { humanizeCode, formatManilaDateTime } from "../../components/ui/display";
import type { Principal } from "../../auth/permissions";
import { V2Operations } from "./v2-operations";
import { useState } from "react";
import { V2RecordExplorer } from "../inventory/v2-record-explorer";
import { selectionFromSearch, type RecordSelection } from "../../services/api/v2-navigation";
type Request = { transfer_id: string; destination_institution_id: string; blood_type: string; component_type: string; quantity: number; status: string; ledger_transaction_id: string | null };
type Reservation = { reservation_id: string; transfer_id: string | null; local_release_id?: string | null; purpose: string; status: string; version: number };
type Event = { command_id: string; resource_id: string; operation: string; status: string; accepted_at: string; ledger_transaction_id: string | null; block_number: string | null; validation_status: string | null };
export function V2TransferEvidenceView({ principal }: { principal: Principal }) {
  const [selected,setSelected] = useState<RecordSelection | undefined>(() => selectionFromSearch(location.search));
  const state = useLiveData<{ requests: Request[]; reservations: Reservation[]; timeline: Event[]; scope?: string; transferSummary?: {status:string;transfer_count:number;unit_count:number}[] }>("/api/v2/transfers");
  return <section><h2>V2 transfers and reservations</h2><p>SIMULATION_ONLY · Request state and reservation lifecycle are separate. Pending commands are not ledger commitments. Use the existing forms below to submit supported commands.</p><V2Operations principal={principal} onRefresh={state.manual}/>{state.error && <p role="alert">{state.error}</p>}{state.data && <>
    <h3>Requests</h3>{state.data.scope === "CITY_AGGREGATE" && <div className="table-wrap"><table className="data-table"><thead><tr><th>Request state</th><th>Requests</th><th>Units</th></tr></thead><tbody>{state.data.transferSummary?.map(row=><tr key={row.status}><td>{row.status}</td><td>{row.transfer_count}</td><td>{row.unit_count}</td></tr>)}</tbody></table></div>}<div className="table-wrap"><table className="data-table"><thead><tr><th>Request</th><th>Destination</th><th>Blood / component</th><th>Quantity</th><th>Request state</th><th>Ledger reference</th></tr></thead><tbody>{state.data.requests.map(r => <tr key={r.transfer_id}><td><button className="button compact mono" aria-label={"Open request " + r.transfer_id} onClick={() => setSelected({kind:"request", id:r.transfer_id})}>{r.transfer_id}</button></td><td>{r.destination_institution_id}</td><td>{humanizeCode(r.blood_type)} / {humanizeCode(r.component_type)}</td><td>{r.quantity}</td><td>{r.status}</td><td className="mono">{r.ledger_transaction_id ?? "Pending — no commitment"}</td></tr>)}</tbody></table></div>
    <h3>Reservation lifecycle</h3><div className="table-wrap"><table className="data-table"><thead><tr><th>Reservation</th><th>Workflow reference</th><th>Purpose</th><th>State</th><th>Version</th></tr></thead><tbody>{state.data.reservations.map(r => <tr key={r.reservation_id}><td><button className="button compact mono" aria-label={"Open reservation " + r.reservation_id} onClick={() => setSelected({kind:"reservation", id:r.reservation_id})}>{r.reservation_id}</button></td><td>{r.transfer_id ?? r.local_release_id ?? "Unavailable"}</td><td>{r.purpose}</td><td>{r.status}</td><td>{r.version}</td></tr>)}</tbody></table></div>
    <h3>Recorded operations</h3><div className="table-wrap"><table className="data-table"><thead><tr><th>Operation</th><th>Command state</th><th>Recorded time</th><th>Ledger reference</th><th>Block / validation</th></tr></thead><tbody>{state.data.timeline.map(e => <tr key={e.command_id}><td>{humanizeCode(e.operation)}</td><td>{e.status}</td><td>{formatManilaDateTime(e.accepted_at)}</td><td className="mono">{e.ledger_transaction_id ?? "Pending — no commitment"}</td><td>{e.block_number ?? "—"} / {e.validation_status ?? "Unverified"}</td></tr>)}</tbody></table></div></>}{selected && <V2RecordExplorer key={selected.kind + selected.id} initial={selected} principal={principal} onClose={() => setSelected(undefined)}/>}</section>;
}
