import { useLiveData } from "../../hooks/use-live-data";
import { humanizeCode, formatManilaDateTime } from "../../components/ui/display";
import type { Principal } from "../../auth/permissions";
import { V2Operations } from "./v2-operations";
type Request = { transfer_id: string; destination_institution_id: string; blood_type: string; component_type: string; quantity: number; status: string; ledger_transaction_id: string };
type Reservation = { reservation_id: string; transfer_id: string; purpose: string; status: string; version: number };
type Event = { command_id: string; resource_id: string; operation: string; status: string; accepted_at: string; ledger_transaction_id: string | null; block_number: string | null; validation_status: string | null };
export function V2TransferEvidenceView({ principal }: { principal: Principal }) {
  const state = useLiveData<{ requests: Request[]; reservations: Reservation[]; timeline: Event[] }>("/api/v2/transfers");
  return <section><h2>V2 transfers and reservations</h2><p>SIMULATION_ONLY · Request state and reservation lifecycle are separate. Pending commands are not ledger commitments. Use the existing forms below to submit supported commands.</p><V2Operations principal={principal} onRefresh={state.manual}/>{state.error && <p role="alert">{state.error}</p>}{state.data && <>
    <h3>Requests</h3><div className="table-wrap"><table className="data-table"><thead><tr><th>Request</th><th>Destination</th><th>Blood / component</th><th>Quantity</th><th>Request state</th><th>Ledger reference</th></tr></thead><tbody>{state.data.requests.map(r => <tr key={r.transfer_id}><td>{r.transfer_id}</td><td>{r.destination_institution_id}</td><td>{humanizeCode(r.blood_type)} / {humanizeCode(r.component_type)}</td><td>{r.quantity}</td><td>{r.status}</td><td className="mono">{r.ledger_transaction_id}</td></tr>)}</tbody></table></div>
    <h3>Reservation lifecycle</h3><div className="table-wrap"><table className="data-table"><thead><tr><th>Reservation</th><th>Request</th><th>Purpose</th><th>State</th><th>Version</th></tr></thead><tbody>{state.data.reservations.map(r => <tr key={r.reservation_id}><td>{r.reservation_id}</td><td>{r.transfer_id}</td><td>{r.purpose}</td><td>{r.status}</td><td>{r.version}</td></tr>)}</tbody></table></div>
    <h3>Recorded operations</h3><div className="table-wrap"><table className="data-table"><thead><tr><th>Operation</th><th>Command state</th><th>Recorded time</th><th>Ledger reference</th><th>Block / validation</th></tr></thead><tbody>{state.data.timeline.map(e => <tr key={e.command_id}><td>{humanizeCode(e.operation)}</td><td>{e.status}</td><td>{formatManilaDateTime(e.accepted_at)}</td><td className="mono">{e.ledger_transaction_id ?? "Pending — no commitment"}</td><td>{e.block_number ?? "—"} / {e.validation_status ?? "Unverified"}</td></tr>)}</tbody></table></div></>}</section>;
}
