import { formatManilaDateTime, humanizeCode, statusClassName } from "../../components/ui/display";
import type { Audit } from "../../services/api/types";

export function AuditView({data}:{data:Audit}) {
  const failures=data.events.filter(item=>["FAILED","REJECTED","ERROR"].includes(item.outcome)).length,ledgerLinked=data.events.filter(item=>item.ledgerTransactionId).length,institutions=new Set(data.events.map(item=>item.institutionDisplayName)).size;
  const summary=<div className="stats audit-summary"><article><span>Permitted events</span><strong>{data.events.length}</strong></article><article><span>Institutions shown</span><strong>{institutions}</strong></article><article className={failures?"accent-critical":""}><span>Failed outcomes</span><strong>{failures}</strong></article><article><span>Ledger-linked</span><strong>{ledgerLinked}</strong></article></div>;
  if(data.events.length===0)return <>{summary}<div className="audit-disclosure"><span aria-hidden="true">⌕</span><p><strong>Redacted application evidence</strong>Exact locations, credentials, certificates, and unrelated institution activity are excluded.</p></div><div className="empty audit-empty"><span className="empty-mark" aria-hidden="true">BL</span><strong>No audit events</strong>No permitted redacted application event is available for this scope.</div></>;
  return <>{summary}<div className="audit-disclosure"><span aria-hidden="true">⌕</span><p><strong>Redacted application evidence</strong>Exact locations, credentials, certificates, and unrelated institution activity are excluded.</p></div><div className="table-wrap"><table className="data-table audit-table"><thead><tr><th>Institution</th><th>Action</th><th>Target</th><th>Outcome</th><th>Correlation</th><th>Ledger reference</th><th>Time</th></tr></thead><tbody>{data.events.map(item=><tr key={item.auditEventId}><td><strong>{item.institutionDisplayName}</strong></td><td>{humanizeCode(item.actionCode)}</td><td>{humanizeCode(item.targetType)}</td><td><span className={statusClassName(item.outcome)}>{humanizeCode(item.outcome)}</span>{item.safeErrorCode&&<small className="safe-error">{humanizeCode(item.safeErrorCode)}</small>}</td><td><span className="evidence-reference mono">{item.correlationId}</span></td><td><span className="evidence-reference mono">{item.ledgerTransactionId??"Not applicable"}</span></td><td className="data-time">{formatManilaDateTime(item.eventTime)}</td></tr>)}</tbody></table></div></>;
}
