import { useState } from "react";
import { InformationHelp } from "../../components/ui/information-help";
import { formatManilaDateTime, humanizeCode, statusClassName } from "../../components/ui/display";
import type { Audit } from "../../services/api/types";

export function AuditView({data}:{data:Audit}) {
  const [search,setSearch]=useState(""),[action,setAction]=useState("ALL");
  const actions=[...new Set(data.events.map(item=>item.actionCode))];
  const query=search.trim().toLowerCase();
  const visible=data.events.filter(item=>(action==="ALL"||item.actionCode===action)&&[item.institutionDisplayName,item.actionCode,humanizeCode(item.actionCode),item.targetType,item.outcome,item.safeErrorCode??"",item.correlationId,item.ledgerTransactionId??""].some(value=>value.toLowerCase().includes(query)));
  const failures=data.events.filter(item=>["FAILED","REJECTED","ERROR"].includes(item.outcome)).length,ledgerLinked=data.events.filter(item=>item.ledgerTransactionId).length,institutions=new Set(data.events.map(item=>item.institutionDisplayName)).size;
  return <div className="blood-bank-audit">
    <div className="stats audit-summary"><article><span>Permitted events</span><strong>{data.events.length}</strong></article><article><span>Institutions shown</span><strong>{institutions}</strong></article><article className={failures?"accent-critical":""}><span>Failed outcomes</span><strong>{failures}</strong></article><article><span>Ledger-linked</span><strong>{ledgerLinked}</strong></article></div>
    <section className="bank-record-card"><header className="bank-section-heading"><h2>Activity records</h2><span>{visible.length} of {data.events.length}</span><InformationHelp label="Activity records">Read the actions and outcomes available within your account’s scope. Search the recorded action or reference, or filter by activity type. Staff names, exact locations and credentials are excluded. A correlation reference tracks an application action; a ledger reference appears only when available.</InformationHelp></header>
      <div className="bank-filter-panel audit-filter-controls"><label>Activity type<span className="requester-select"><select aria-label="Activity type" value={action} onChange={event=>setAction(event.target.value)}><option value="ALL">All activities</option>{actions.map(value=><option key={value} value={value}>{humanizeCode(value)}</option>)}</select></span></label><label className="bank-search">Search activity<input type="search" value={search} placeholder="Action, outcome or reference…" onChange={event=>setSearch(event.target.value)}/></label></div>
      {visible.length?<div className="table-wrap"><table className="data-table audit-table"><thead><tr><th>Date &amp; time</th><th>Activity</th><th>Institution</th><th>Outcome</th><th>Correlation</th><th>Ledger reference</th></tr></thead><tbody>{visible.map(item=><tr key={item.auditEventId}><td className="data-time">{formatManilaDateTime(item.eventTime)}</td><td><strong>{humanizeCode(item.actionCode)}</strong><small className="v2-secondary-id">{humanizeCode(item.targetType)}</small></td><td>{item.institutionDisplayName}</td><td><span className={statusClassName(item.outcome)}>{humanizeCode(item.outcome)}</span>{item.safeErrorCode&&<small className="safe-error">{humanizeCode(item.safeErrorCode)}</small>}</td><td><span title={item.correlationId} className="evidence-reference mono">{item.correlationId}</span></td><td><span title={item.ledgerTransactionId??undefined} className="evidence-reference mono">{item.ledgerTransactionId??"Not applicable"}</span></td></tr>)}</tbody></table></div>:<div className="requester-records-empty"><strong>{data.events.length?"No activity matches your filters":"No activity recorded"}</strong><span>{data.events.length?"Try another activity type or search.":"Permitted activity records will appear here."}</span></div>}
    </section>
  </div>;
}
