import assert from "node:assert/strict";
import { randomBytes } from "node:crypto";
import test from "node:test";
import { buildApp } from "../src/app.js";
import type { ApiConfig } from "../src/config.js";
import type { ApplicationReadRepository } from "../src/application-read.js";
import { deriveVerifier, type CredentialRecord, type SessionRepository } from "../src/session.js";
import type { RoleId } from "../src/web-access.js";
import { MemoryRepository } from "./test-support.js";
const origin="http://127.0.0.1:5174",config:ApiConfig={host:"127.0.0.1",port:3000,jwtSecret:"sprint5-read-test-secret-not-deployed",operatorId:"USR_SYNTH_CAPTURE",operatorCredential:"synthetic-test-credential",workerConfigured:false,webOrigin:origin,webCookieSecure:false};
class Sessions implements SessionRepository{record!:CredentialRecord;active=new Map<string,string>();async findCredential(username:string){return username===this.record.username?this.record:null}async createSession(input:{sessionId:string;userId:string;tokenDigest:string}){this.active.set(input.sessionId,input.tokenDigest)}async restoreSession(id:string,digest:string){return this.active.get(id)===digest?this.record:null}async revokeSession(id:string){this.active.delete(id)}}
class Reads implements ApplicationReadRepository{calls:string[]=[];async listInventoryUnits(id:string){this.calls.push(`units:${id}`);return[{unitId:"UNIT_SYNTH_VIEW_01",institutionId:id,bloodType:"A_POSITIVE",component:"RED_BLOOD_CELLS",collectedAt:"2026-08-19T00:00:00.000Z",expiresAt:"2026-08-22T00:00:00.000Z",inventoryStatus:"AVAILABLE" as const,ledgerVersion:1,ledgerTransactionId:"TX_SYNTH_VIEW_01",projectedAt:"2026-08-20T00:00:00.000Z",classification:"SIMULATION_ONLY" as const}]}async listInventoryAggregates(id?:string){this.calls.push(`aggregates:${id??"CITY"}`);return[{institutionId:id??"INST_SYNTH_01",institutionDisplayName:"Synthetic Hospital 01",bloodType:"A_POSITIVE",component:"RED_BLOOD_CELLS",inventoryStatus:"AVAILABLE" as const,confirmedCount:1,lastProjectedAt:"2026-08-20T00:00:00.000Z"}]}async listPendingScans(id?:string){this.calls.push(`pending:${id??"CITY"}`);return[{status:"QUEUED",count:2}]}async listAlerts(id:string,user:string){this.calls.push(`alerts:${id}:${user}`);return[{alertId:"ALRT_"+"A".repeat(40),institutionId:id,alertType:"EXPIRY_WARNING",severity:"WARNING",unitId:"UNIT_SYNTH_VIEW_01",bloodType:"A_POSITIVE",component:"RED_BLOOD_CELLS",inventoryStatus:"AVAILABLE",expiresAt:"2026-08-22T00:00:00.000Z",evaluatedAt:"2026-08-20T00:00:00.000Z",status:"OPEN",acknowledged:false,policyVersion:"SYNTHETIC_INVENTORY_V1",classification:"SIMULATION_ONLY" as const}]}async listAlertAggregates(){this.calls.push("alert-aggregates:CITY");return[{institutionId:"INST_SYNTH_01",institutionDisplayName:"Synthetic Hospital 01",alertType:"STOCK_SHORTAGE",severity:"WARNING",status:"OPEN",count:1,lastEvaluatedAt:"2026-08-20T00:00:00.000Z"}]}async listTransfers(id?:string,perspective?:"SOURCE"|"DESTINATION"){this.calls.push(`transfers:${id??"CITY"}:${perspective??"ALL"}`);return[{transferId:"TRF_SYNTH_VIEW_01",sourceInstitutionId:"INST_MEDIATRIX",destinationInstitutionId:id??"INST_SYNTH_01",bloodType:"A_POSITIVE",component:"RED_BLOOD_CELLS",quantity:1,urgency:"ROUTINE",requestTime:"2026-08-20T00:00:00.000Z",status:"PENDING",reasonCode:null,ledgerVersion:1,ledgerTransactionId:"TX_SYNTH_TRANSFER_VIEW",correlationId:"CORR_"+"A".repeat(32),projectedAt:"2026-08-20T00:00:00.000Z",dispatchEvidenceRecorded:false,receiptEvidenceRecorded:false,classification:"SIMULATION_ONLY" as const}]}}
async function fixture(roleId:RoleId){const password=randomBytes(24).toString("base64url"),saltHex=randomBytes(16).toString("hex"),sessions=new Sessions(),reads=new Reads();sessions.record={userId:"USR_SYNTH_VIEW_01",username:"synth_view_01",displayName:"Synthetic Viewer 01",institutionId:["ROLE-01","ROLE-02"].includes(roleId)?"INST_MEDIATRIX":"INST_SYNTH_01",institutionDisplayName:["ROLE-01","ROLE-02"].includes(roleId)?"Synthetic Mediatrix 01":roleId==="ROLE-05"?"Synthetic System 01":"Synthetic Hospital 01",institutionCategory:roleId==="ROLE-04"?"REGULATOR":roleId==="ROLE-05"?"SYSTEM":"HOSPITAL",roleId,saltHex,verifierHex:await deriveVerifier(password,saltHex)};const app=await buildApp(new MemoryRepository(),config,()=>new Date(),sessions,reads);const login=await app.inject({method:"POST",url:"/api/v1/auth/session",headers:{origin},payload:{username:sessions.record.username,password}});assert.equal(login.statusCode,200);return{app,reads,cookie:String(login.headers["set-cookie"]).split(";")[0]}}

test("ROLE-01 dashboard and inventory execute only institution-scoped reads",async()=>{const{app,reads,cookie}=await fixture("ROLE-01");const dashboard=await app.inject({method:"GET",url:"/api/v1/dashboard",headers:{cookie}});assert.equal(dashboard.json().scope,"INSTITUTION");assert.equal(dashboard.json().inventory[0].confirmedCount,1);assert.equal(dashboard.json().pendingScans[0].count,2);const inventory=await app.inject({method:"GET",url:"/api/v1/inventory",headers:{cookie}});assert.equal(inventory.json().units.length,1);assert.deepEqual(reads.calls,["aggregates:INST_MEDIATRIX","pending:INST_MEDIATRIX","units:INST_MEDIATRIX"]);await app.close()});

test("ROLE-03 shares hospital composition but receives aggregate-only dashboard and no inventory route",async()=>{const{app,reads,cookie}=await fixture("ROLE-03");const dashboard=await app.inject({method:"GET",url:"/api/v1/dashboard",headers:{cookie}});assert.equal(dashboard.json().composition,"OPERATIONAL");assert.equal(dashboard.json().scope,"CITY_AGGREGATE");assert.equal((await app.inject({method:"GET",url:"/api/v1/inventory",headers:{cookie}})).statusCode,403);assert.deepEqual(reads.calls,["aggregates:CITY","pending:CITY"]);await app.close()});

test("ROLE-04 receives regulatory aggregates without unit-detail queries",async()=>{const{app,reads,cookie}=await fixture("ROLE-04");assert.equal((await app.inject({method:"GET",url:"/api/v1/dashboard",headers:{cookie}})).json().composition,"REGULATORY");const inventory=await app.inject({method:"GET",url:"/api/v1/inventory",headers:{cookie}});assert.equal(inventory.json().scope,"CITY_AGGREGATE");assert.equal(inventory.json().units.length,0);assert.equal(reads.calls.some(call=>call.startsWith("units:")),false);await app.close()});

test("administrative dashboard performs no clinical or inventory read",async()=>{const{app,reads,cookie}=await fixture("ROLE-05");const dashboard=await app.inject({method:"GET",url:"/api/v1/dashboard",headers:{cookie}});assert.equal(dashboard.json().composition,"ADMINISTRATIVE");assert.deepEqual(reads.calls,[]);assert.equal((await app.inject({method:"GET",url:"/api/v1/inventory",headers:{cookie}})).statusCode,403);await app.close()});


test("ROLE-03 reads only own destination transfers and own detailed alerts",async()=>{const{app,reads,cookie}=await fixture("ROLE-03");assert.equal((await app.inject({method:"GET",url:"/api/v1/alerts",headers:{cookie}})).json().scope,"INSTITUTION");assert.equal((await app.inject({method:"GET",url:"/api/v1/transfers",headers:{cookie}})).json().scope,"DESTINATION_INSTITUTION");assert.deepEqual(reads.calls,["alerts:INST_SYNTH_01:USR_SYNTH_VIEW_01","transfers:INST_SYNTH_01:DESTINATION"]);await app.close()});

test("ROLE-04 reads alert and transfer aggregates without institution detail query",async()=>{const{app,reads,cookie}=await fixture("ROLE-04");const alerts=await app.inject({method:"GET",url:"/api/v1/alerts",headers:{cookie}});assert.equal(alerts.json().alerts.length,0);assert.equal(alerts.json().aggregates.length,1);assert.equal((await app.inject({method:"GET",url:"/api/v1/transfers",headers:{cookie}})).json().scope,"CITY_AGGREGATE");assert.deepEqual(reads.calls,["alert-aggregates:CITY","transfers:CITY:ALL"]);await app.close()});

test("ROLE-01 reads only source transfer history",async()=>{const{app,reads,cookie}=await fixture("ROLE-01");await app.inject({method:"GET",url:"/api/v1/transfers",headers:{cookie}});assert.deepEqual(reads.calls,["transfers:INST_MEDIATRIX:SOURCE"]);await app.close()});
