import {useEffect,useRef,useState,type FormEvent,type ReactNode} from "react";
import {InformationHelp} from "../../components/ui/information-help";
import {requestJson} from "../../services/api/client";
import {newMutationKeys,type MutationKeys} from "../../services/api/mutation-keys";
const steps=["Facility","Qualification","Primary account","Documents"];
type Category="BLOOD_BANK"|"REQUESTOR";
function Placeholder({label,type="text",options}:{label:string;type?:string;options?:string[]}){return <label>{label}{options?<span className="requester-select"><select aria-label={label} disabled defaultValue={options[0]}>{options.map(value=><option key={value}>{value}</option>)}</select></span>:<input disabled type={type} placeholder="Not available yet"/>}</label>;}
function Section({title,help,children}:{title:string;help:string;children:ReactNode}){return <section className="application-section"><header className="application-section-heading"><h3>{title}</h3><InformationHelp label={title}>{help}</InformationHelp></header>{children}</section>;}
export function SyntheticApplication(){
 const[category,setCategory]=useState<Category>(),[step,setStep]=useState(1),[fields,setFields]=useState<Record<string,string>>({}),[confirmation,setConfirmation]=useState(""),[attested,setAttested]=useState(false),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[applicationId,setApplicationId]=useState("");
 const attempt=useRef<{keys:MutationKeys;payload:Record<string,unknown>}|undefined>(undefined),form=useRef<HTMLFormElement>(null);
 function update(key:string,value:string){attempt.current=undefined;setMessage("");setFields(old=>({...old,[key]:value}));}
 function choose(value:Category){setCategory(value);setStep(1);setFields({});setConfirmation("");setAttested(false);setMessage("");attempt.current=undefined;}
 const bank=category==="BLOOD_BANK";
 function input(label:string,key:string,type="text",placeholder=""){return <label>{label}<input aria-label={label} type={type} autoComplete="off" required minLength={key==="password"?12:undefined} maxLength={key==="password"?128:undefined} value={fields[key]??""} placeholder={placeholder} disabled={busy} onChange={event=>update(key,event.target.value)}/></label>;}
 function next(){if(!form.current?.reportValidity())return;if(step===3&&fields.password!==confirmation){setMessage("Passwords do not match.");return;}setMessage("");setStep(value=>value+1);}
 async function submit(event:FormEvent){event.preventDefault();if(step<4){next();return;}if(busy)return;if(!category||!attested||!["invitationSecret","institutionDisplayName","locality","genericContact","licenseReference","applicationReason","password"].every(key=>fields[key]?.trim())||fields.password!==confirmation){setMessage("Complete the supported fields and confirm your password before submitting.");return;}setBusy(true);setMessage("");const current=attempt.current??{keys:newMutationKeys(),payload:{...fields,category,attested:true,correlationId:""}};if(!attempt.current){current.payload.correlationId=current.keys.correlationId;attempt.current=current;}
 try{const result=await requestJson<{applicationId:string;status:string}>("/api/v2/onboarding/applications",{method:"POST",headers:{"Idempotency-Key":current.keys.idempotencyKey},body:JSON.stringify(current.payload)});setApplicationId(result.applicationId);setFields({});setConfirmation("");attempt.current=undefined;setCategory(undefined);setStep(1);setAttested(false);setMessage("Basic application submitted. Extended qualification fields and documents were not sent. Save the reference and use your applicant password to check its status.");}catch(reason){setMessage(reason instanceof Error?reason.message:"Submission failed.");}finally{setBusy(false);}}
 return <div className="access-application-workspace">
 {!category?<div className="application-choice"><div className="auth-card-heading"><p className="eyebrow">Institution application</p><h2>How will your facility participate?</h2><p>Choose the application that matches your facility.</p></div><div className="application-type-grid">
 <button type="button" onClick={()=>choose("BLOOD_BANK")}><span className="application-type-icon" aria-hidden="true">▣</span><strong>Apply as a Blood Bank</strong><p>For a facility supplying, storing, processing and issuing blood.</p><ul><li>Blood-service license and qualifications</li><li>Responsible professional roles</li><li>Facility assessment documents</li></ul><b>Start Blood Bank Application →</b></button>
 <button type="button" onClick={()=>choose("REQUESTOR")}><span className="application-type-icon requestor" aria-hidden="true">◇</span><strong>Apply as a Requestor</strong><p>For a facility requesting and receiving blood for transfusion.</p><ul><li>Facility license and receiving authority</li><li>Receiving capability and referral facility</li><li>Authorization documents</li></ul><b>Start Requestor Application →</b></button></div><p className="application-support-note">A PRC invitation is required. Use synthetic institution details and generic contacts only.</p></div>:<form ref={form} className="application-form" onSubmit={event=>void submit(event)}>
 <header className="application-header"><button type="button" className="text-button" disabled={busy} onClick={()=>{setCategory(undefined);setFields({});setConfirmation("");setAttested(false);attempt.current=undefined;setMessage("");}}>← Change application</button><p className="eyebrow">{bank?"Blood Bank application":"Requestor application"}</p><h2>Institution qualification</h2><p>Step {step} of 4 · {steps[step-1]}</p></header>
 <div className="application-steps" aria-label="Application progress">{steps.map((label,index)=><div className={step>=index+1?"active":""} aria-current={step===index+1?"step":undefined} key={label}><span>{index+1}</span><b>{label}</b></div>)}</div>
 <p className="application-support-note">Extended fields and document attachments are shown for review and remain unavailable. Submission sends only supported application details.</p>
 {step===1&&<p className="application-support-note">A PRC invitation is required. Use synthetic institution details and generic contacts only.</p>}
 {step===1&&<Section title="Facility information" help="Enter your institution’s basic details and private PRC invitation. Additional registration fields will become available when supported by the application service."><div className="application-fields">
 {input("Facility name","institutionDisplayName","text","Synthetic Facility Alpha")}<Placeholder label="Registered legal name"/><Placeholder label="Ownership" options={["Private","Government"]}/><Placeholder label="Facility classification" options={["Level 1 Hospital","Level 2 Hospital","Level 3 Hospital","Other Licensed Health Facility"]}/><Placeholder label="Complete address"/>{input("City / Municipality","locality","text","Synthetic locality")}<Placeholder label="Province"/><Placeholder label="Official phone"/>{input("Official facility email","genericContact","email","facility@sample.bloodledger")}<Placeholder label="Hospital / Health Facility LTO number"/><Placeholder label="LTO expiration" type="date"/>{input("Private invitation secret","invitationSecret","password")}</div></Section>}
 {step===2&&<><Section title={bank?"Blood Service Facility qualification":"Requestor receiving capability"} help="License references currently use the basic application contract. Detailed qualification, personnel and capability declarations are placeholders and are not verified."><div className="application-fields">{bank&&<Placeholder label="BSF category" options={["Blood Bank","Blood Bank with Additional Functions","Blood Center"]}/>} {input(bank?"DOH BSF LTO number":"Blood Station ATO / authorization number","licenseReference","text","SYNTH-LICENSE-REFERENCE")}<Placeholder label="License / authority expiration" type="date"/>{bank&&<><Placeholder label="Head of Blood Service Facility"/><Placeholder label="Physician PRC license number"/></>}<Placeholder label="Medical technologist-in-charge"/><Placeholder label="Medical technologist PRC license"/>{!bank&&<Placeholder label="Referral blood bank / supplying BSF"/>}</div><div className="qualification-checklist"><strong>Applicant declaration of capability</strong>{[bank?"Blood storage, processing, compatibility testing, issuance and transport procedures are documented.":"Blood storage, compatibility testing, transfusion and hemovigilance procedures are documented.","Required personnel, equipment, power continuity and contingency procedures are available.","The facility agrees to verification against DOH/CHD licensing records."].map(label=><label key={label}><input type="checkbox" disabled/><span>{label}</span></label>)}</div></Section><Section title="Application reason" help="Provide a short synthetic reason for the institution’s application. Do not include personal or clinical information.">{input("Application reason","applicationReason","text","SYNTHETIC_PARTICIPATION")}</Section></>}
 {step===3&&<Section title="Facility Account applicant" help="The applicant password is used to check this application’s status. Institution login credentials are provisioned separately during activation. Applicant identity and account-email fields below are not collected yet."><div className="application-fields"><Placeholder label="Full name"/><Placeholder label="Official position" options={[bank?"Blood Bank Head":"Facility Administrator"]}/><Placeholder label="Employee ID"/><Placeholder label="Facility Account email" type="email"/>{input("Applicant password","password","password")}<label>Confirm password<input type="password" autoComplete="off" required minLength={12} maxLength={128} value={confirmation} disabled={busy} onChange={event=>{setConfirmation(event.target.value);setMessage("");}}/></label></div><p className="application-support-note">Use 12–128 characters. Passwords are never shown on Profile.</p></Section>}
 {step===4&&<Section title="Supporting documents & declaration" help="The document cards follow the reference application. Upload, storage and licensing verification are not connected, so no files can be selected or submitted."><div className="document-preview-grid">{(bank?[["Hospital / Health Facility LTO","Required"],["DOH Blood Service Facility LTO","Required"],["BSF assessment, personnel and equipment documents","Required"]]:[["Hospital / Health Facility LTO","Required"],["Blood Station ATO or transfusion-service authorization","Required"],["Referral agreement or facility capability documents","Optional"]]).map(([label,requirement])=><div key={label}><span aria-hidden="true">↥</span><strong>{label}</strong><small>{requirement} · Attachment unavailable</small><button type="button" disabled>Attach document</button></div>)}</div><label className="declaration-preview"><input type="checkbox" required checked={attested} disabled={busy} onChange={event=>{setAttested(event.target.checked);attempt.current=undefined;}}/><span>I confirm these application details are synthetic and contain no personal or clinical information.</span></label></Section>}
 {message&&<p className="auth-error" role="alert">{message}</p>}<footer className="application-footer">{step>1?<button className="button compact" type="button" disabled={busy} onClick={()=>{setMessage("");setStep(value=>value-1);}}>Previous</button>:<span/>}{step<4?<button className="button primary compact" type="button" onClick={next}>Continue</button>:<button className="button primary compact" type="submit" disabled={busy||!attested}>{busy?"Submitting…":"Submit for PRC review"}</button>}</footer></form>}
 {!category&&message&&<p className="application-result" role="status">{message}{applicationId&&<strong className="mono">{applicationId}</strong>}</p>}
 <ApplicantStatus initialReference={applicationId}/>
 </div>;
}
function ApplicantStatus({initialReference}:{initialReference:string}){
 const[reference,setReference]=useState(initialReference),[password,setPassword]=useState(""),[application,setApplication]=useState<{applicationId:string;status:string;version:number}>(),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
 useEffect(()=>{setReference(initialReference);},[initialReference]);
 async function login(event:FormEvent){event.preventDefault();setBusy(true);setMessage("");try{await requestJson("/api/v2/onboarding/applicant/session",{method:"POST",body:JSON.stringify({applicationId:reference,password})});setPassword("");setApplication(await requestJson("/api/v2/onboarding/applicant/status"));}catch(reason){setApplication(undefined);setMessage(reason instanceof Error?reason.message:"Status unavailable.");}finally{setBusy(false);}}
 async function withdraw(){if(!application)return;setBusy(true);const keys=newMutationKeys();try{await requestJson("/api/v2/onboarding/applicant/withdraw",{method:"POST",headers:{"Idempotency-Key":keys.idempotencyKey},body:JSON.stringify({expectedVersion:application.version,correlationId:keys.correlationId,reasonCode:"SYNTHETIC_WITHDRAWAL"})});setApplication(await requestJson("/api/v2/onboarding/applicant/status"));}catch(reason){setMessage(reason instanceof Error?reason.message:"Withdrawal failed.");}finally{setBusy(false);}}
 return <details className="application-status-panel"><summary>Check an existing application</summary><form className="auth-form" onSubmit={event=>void login(event)}><label>Application reference<input value={reference} onChange={event=>{setApplication(undefined);setReference(event.target.value);}} required/></label><label>Applicant password<input type="password" autoComplete="off" value={password} onChange={event=>setPassword(event.target.value)} required/></label><button className="button compact" disabled={busy}>Check status</button></form>{application&&<div className="application-status-result"><p>{application.status} · Version {application.version}</p>{["SUBMITTED","UNDER_REVIEW"].includes(application.status)&&<button className="button compact" disabled={busy} onClick={()=>void withdraw()}>Withdraw application</button>}<button className="button compact" onClick={()=>{setApplication(undefined);setPassword("");void requestJson("/api/v2/onboarding/applicant/session",{method:"DELETE"});}}>End applicant session</button></div>}{message&&<p className="auth-error" role="status">{message}</p>}</details>;
}
