import {expect,test,type Page} from "@playwright/test";
const request={transfer_id:"TRF_INCOMING",source_institution_id:"INST_MEDIATRIX",destination_institution_id:"INST_REQUESTER",blood_type:"O_POSITIVE",component_type:"PACKED_RED_BLOOD_CELLS",quantity:3,urgency:"URGENT",request_time:"2026-10-10T00:00:00Z",status:"REQUESTED",ledger_transaction_id:null};
const reservation={reservation_id:"RES_INCOMING",transfer_id:request.transfer_id,purpose:"TRANSFER",status:"IN_TRANSIT",version:2,institution_id:"INST_MEDIATRIX",destination_institution_id:"INST_REQUESTER"};
async function setup(page:Page,status:()=>number=()=>200){await page.route("**/api/**",async route=>{const path=new URL(route.request().url()).pathname;let code=200,body:unknown;
if(path==="/api/v1/auth/session")body={principal:{userId:"USR_REQUESTER",displayName:"Synthetic Requester",institutionId:"INST_REQUESTER",institutionDisplayName:"Synthetic Requester Hospital",roleId:"ROLE-03",roleDisplayName:"Requester",accountId:"ACC_REQUESTER",accountCategory:"REQUESTOR",permissions:["dashboard:operational","transfers:read","transfers:write","profile:read"],classification:"SIMULATION_ONLY"}};
else if(path==="/api/v2/transfers"){code=status();body=code===200?{requests:[request,{...request,transfer_id:"TRF_RECEIVED"},{...request,transfer_id:"TRF_FOREIGN",destination_institution_id:"INST_FOREIGN"}],reservations:[reservation,{...reservation,reservation_id:"RES_RECEIVED",transfer_id:"TRF_RECEIVED",status:"RECEIVED"},{...reservation,reservation_id:"RES_FOREIGN",transfer_id:"TRF_FOREIGN",destination_institution_id:"INST_FOREIGN",status:"RECEIVED"}],timeline:[],classification:"SIMULATION_ONLY"}:{error:{message:"Synthetic failure"}};}
else if(path==="/api/v2/reservations/RES_INCOMING")body={reservationId:reservation.reservation_id,purpose:"TRANSFER",status:"IN_TRANSIT",version:2,sourceInstitutionId:"INST_MEDIATRIX",destinationInstitutionId:"INST_REQUESTER",transferId:request.transfer_id,localReleaseId:null,preparedAt:request.request_time,preparedEvidencePresent:true,updatedAt:request.request_time,components:[],classification:"SIMULATION_ONLY"};
else{code=404;body={error:{message:"Unavailable fixture"}};}
await route.fulfill({status:code,contentType:"application/json",body:JSON.stringify(body)});});}
const image={name:"synthetic-label.png",mimeType:"image/png",buffer:Buffer.from("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jB1kAAAAASUVORK5CYII=","base64")};
test("receipt history only shows own received reservations and scanner does not submit",async({page})=>{let mutations=0;page.on("request",req=>{if(req.method()==="POST")mutations++;});await setup(page);await page.goto("/receipts");await expect(page.getByRole("link",{name:"Blood Unit Receipt",exact:true})).toBeVisible();await expect(page.getByRole("button",{name:"Open receipt RES_RECEIVED"})).toBeVisible();await expect(page.getByText("TRF_FOREIGN",{exact:true})).toHaveCount(0);await expect(page.locator(".receipt-history-table").getByText("TRF_INCOMING",{exact:true})).toHaveCount(0);
await page.getByRole("button",{name:"Open Mobile Receipt Scanner"}).click();const dialog=page.getByRole("dialog");await expect(dialog.getByLabel("Transaction Type")).toHaveCount(0);await expect(dialog.getByLabel("Incoming transfer",{exact:true})).toHaveCount(0);await expect(dialog.getByRole("tab",{name:"Scan",exact:true})).toHaveAttribute("aria-selected","true");await expect(dialog.getByText("Outbound",{exact:true})).toHaveCount(0);await dialog.getByLabel("Blood-unit label image").setInputFiles(image);await expect(dialog.getByAltText("Selected blood-unit label preview")).toBeVisible();await expect(dialog.getByRole("button",{name:"Confirm inbound receipt",exact:true})).toBeDisabled();expect(mutations).toBe(0);await dialog.getByRole("button",{name:"Close receipt scanner",exact:true}).click();await expect(dialog).toHaveCount(0);await expect(page.getByRole("button",{name:"Open Mobile Receipt Scanner"})).toBeFocused();await page.getByRole("button",{name:"Open Mobile Receipt Scanner"}).click();await expect(page.getByAltText("Selected blood-unit label preview")).toHaveCount(0);await page.keyboard.press("Escape");await expect(dialog).toHaveCount(0);await page.getByRole("button",{name:"Open Mobile Receipt Scanner"}).click();await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);});
test("access denial clears receipt records and disables scanner launch",async({page})=>{let code=200;await setup(page,()=>code);await page.goto("/receipts");await expect(page.getByRole("button",{name:"Open receipt RES_RECEIVED"})).toBeVisible();code=403;await page.getByRole("button",{name:"Refresh",exact:true}).click();await expect(page.getByRole("button",{name:"Open receipt RES_RECEIVED"})).toHaveCount(0);await expect(page.getByRole("button",{name:"Open Mobile Receipt Scanner"})).toBeDisabled();});

test("manual tab immediately displays an inline form and keeps previews local",async({page})=>{let posts=0;page.on("request",req=>{if(req.method()==="POST")posts++;});await setup(page);await page.goto("/receipts");await page.getByRole("button",{name:"Open Mobile Receipt Scanner"}).click();const scanner=page.getByRole("dialog",{name:"Mobile Receipt Scanner",exact:true});await scanner.getByRole("tab",{name:"Scan",exact:true}).focus();await page.keyboard.press("ArrowRight");await expect(scanner.getByRole("tab",{name:"Manual",exact:true})).toBeFocused();const form=scanner.getByRole("form",{name:"Manual blood unit entry",exact:true});await expect(form.getByLabel("Unit ID",{exact:true})).toBeVisible();await expect(page.getByRole("dialog")).toHaveCount(1);await expect(scanner.getByRole("button",{name:"Enter unit details"})).toHaveCount(0);await expect(form.getByRole("button",{name:"Preview Entry",exact:true})).toBeDisabled();await form.getByLabel("Unit ID",{exact:true}).fill("SYNTHETIC-LABEL-ONLY");await form.getByLabel("Expiration Date",{exact:true}).fill("2026-12-10");await form.getByLabel("Source Facility",{exact:true}).selectOption("INST_MEDIATRIX");await form.getByRole("button",{name:"Preview Entry",exact:true}).click();await expect(form).toBeVisible();await expect(scanner.getByRole("heading",{name:"Inbound Preview",exact:true})).toBeVisible();await expect(scanner.getByText("SYNTHETIC-LABEL-ONLY",{exact:true})).toBeVisible();await expect(scanner.getByRole("button",{name:"Confirm inbound receipt",exact:true})).toBeDisabled();expect(posts).toBe(0);await scanner.getByRole("tab",{name:"Scan",exact:true}).click();await scanner.getByRole("tab",{name:"Manual",exact:true}).click();await expect(form.getByLabel("Unit ID",{exact:true})).toHaveValue("SYNTHETIC-LABEL-ONLY");await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await form.getByRole("button",{name:"Preview Entry",exact:true}).focus();await page.keyboard.press("Escape");await expect(scanner).toHaveCount(0);await page.getByRole("button",{name:"Open Mobile Receipt Scanner"}).click();await scanner.getByRole("tab",{name:"Manual",exact:true}).click();await expect(form.getByLabel("Unit ID",{exact:true})).toHaveValue("");});
