import {readFile} from "node:fs/promises";
import {test,expect,type Page} from "@playwright/test";
const base={donationId:"DON_SYNTH_BANK",issuerInstitutionId:"INST_MEDIATRIX",collectedAt:"2026-10-01T00:00:00Z",institutionId:"INST_MEDIATRIX",inventoryStatus:"AVAILABLE",expiryState:"CURRENT",reservationId:null,reservationVersion:null,inventoryVersion:2,policyVersion:"INTERVIEW_DERIVED_CORE_V2",classification:"SIMULATION_ONLY"};
const components=[{...base,componentId:"COMP_SYNTH_PRBC",bloodType:"O_NEGATIVE",componentType:"PACKED_RED_BLOOD_CELLS",expiresAt:"2026-11-02T00:00:00Z"},{...base,componentId:"COMP_SYNTH_PLATELET",bloodType:"A_POSITIVE",componentType:"PLATELETS",expiresAt:"2026-11-01T00:00:00Z"}];
async function setup(page:Page){await page.route("**/api/**",async route=>{const path=new URL(route.request().url()).pathname;let body:unknown={},status=200;
if(path==="/api/v1/auth/session")body={principal:{accountId:"ACC_SYNTH_BANK",accountCategory:"BLOOD_BANK",userId:"USR_SYNTH_BANK",displayName:"Synthetic Institution",institutionId:"INST_MEDIATRIX",institutionDisplayName:"Synthetic Mediatrix",roleId:"ROLE-02",roleDisplayName:"Coordinator",permissions:["dashboard:operational","inventory:read","transfers:read","audit:read","profile:read"],operators:[{operatorId:"OP_SYNTH_BANK",roleId:"ROLE-02",capabilityProfile:"ROLE",actionCapabilities:["inventory:local-release","inventory:capture","transfer:request"]}],classification:"SIMULATION_ONLY"}};
else if(path==="/api/v2/dashboard")body={composition:"OPERATIONAL",scope:"INSTITUTION",inventory:[{institutionId:"INST_MEDIATRIX",bloodType:"O_POSITIVE",component:"PACKED_RED_BLOOD_CELLS",inventoryStatus:"AVAILABLE",confirmedCount:3,lastProjectedAt:"2026-10-10T00:00:00Z"}],pendingScans:[],lastSuccessfulProjectionAt:"2026-10-10T00:00:00Z",classification:"SIMULATION_ONLY"};
else if(path==="/api/v2/components")body={scope:"INSTITUTION",components,classification:"SIMULATION_ONLY"};
else if(path.startsWith("/api/v2/components/"))body=components.find(c=>path.endsWith(c.componentId));
else if(path==="/api/v2/reports/inbound-intake")body={scope:"INSTITUTION",statuses:{},includedInventoryStatuses:["COMMITTED"],excludedFromInventory:["QUEUED"],classification:"SIMULATION_ONLY"};
else if(path==="/api/v2/transfers")body={scope:"INSTITUTION",requests:[{transfer_id:"TRF_SYNTH_BANK",source_institution_id:"INST_MEDIATRIX",destination_institution_id:"INST_SYNTH_METROLIPA",blood_type:"O_NEGATIVE",component_type:"PACKED_RED_BLOOD_CELLS",quantity:2,urgency:"ROUTINE",status:"REQUESTED",ledger_transaction_id:null}],reservations:[{reservation_id:"RES_SYNTH_BANK",transfer_id:"TRF_SYNTH_BANK",purpose:"TRANSFER",status:"PREPARED",version:2}],timeline:[],classification:"SIMULATION_ONLY"};
else if(path==="/api/v2/reservations/RES_SYNTH_BANK")body={reservationId:"RES_SYNTH_BANK",purpose:"TRANSFER",status:"PREPARED",version:2,sourceInstitutionId:"INST_MEDIATRIX",destinationInstitutionId:"INST_SYNTH_METROLIPA",transferId:"TRF_SYNTH_BANK",localReleaseId:null,preparedAt:"2026-10-10T00:00:00Z",preparedEvidencePresent:true,updatedAt:"2026-10-10T00:00:00Z",components:[],classification:"SIMULATION_ONLY"};
else if(path==="/api/v2/audit")body={scope:"INSTITUTION",classification:"SIMULATION_ONLY",events:[{auditEventId:"AUD_SYNTH_OK",institutionDisplayName:"Synthetic Mediatrix",actionCode:"INTAKE_COMMITTED",targetType:"COMPONENT",outcome:"SUCCESS",safeErrorCode:null,correlationId:"CORR_SYNTH_INTAKE",ledgerTransactionId:"TX_SYNTH_INTAKE",eventTime:"2026-10-10T00:00:00Z"},{auditEventId:"AUD_SYNTH_FAIL",institutionDisplayName:"Synthetic Mediatrix",actionCode:"LOCAL_RELEASE",targetType:"RESERVATION",outcome:"FAILED",safeErrorCode:"INSUFFICIENT_STOCK",correlationId:"CORR_SYNTH_RELEASE",ledgerTransactionId:null,eventTime:"2026-10-10T01:00:00Z"}]};
else{status=404;body={error:{message:"Fixture unavailable"}};}await route.fulfill({status,contentType:"application/json",body:JSON.stringify(body)});});}
test("bank inventory filters confirmed components and preserves detail/expiry evidence",async({page})=>{await setup(page);await page.goto("/inventory");await expect(page.getByRole("button",{name:"Open component COMP_SYNTH_PRBC",exact:true})).toBeVisible();const rows=page.locator(".inventory-table tbody tr");await expect(rows.first()).toContainText("COMP_SYNTH_PLATELET");await page.getByLabel("Blood type filter",{exact:true}).selectOption("O_NEGATIVE");await expect(rows).toHaveCount(1);await expect(rows).toContainText("COMP_SYNTH_PRBC");await page.getByLabel("Component filter",{exact:true}).selectOption("PLATELETS");await expect(page.getByText("No components match your filters",{exact:true})).toBeVisible();await page.getByLabel("Component filter",{exact:true}).selectOption("PACKED_RED_BLOOD_CELLS");await expect(rows).toHaveCount(1);await page.getByLabel("Search inventory",{exact:true}).fill("missing");await expect(page.getByText("No components match your filters",{exact:true})).toBeVisible();await page.getByLabel("Search inventory",{exact:true}).fill("");await page.getByRole("button",{name:"Open component COMP_SYNTH_PRBC",exact:true}).click();await expect(page.getByRole("dialog",{name:"Component details",exact:true})).toBeVisible();await expect(page.getByText("Label current",{exact:true}).last()).toBeVisible();await page.getByRole("button",{name:"Close record details",exact:true}).click();await page.getByRole("button",{name:"Blood Inventory page information",exact:true}).focus();await expect(page.getByRole("tooltip").filter({hasText:"Filter by blood type"})).toBeVisible();await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);});
test("bank transfers separate request and reservation filters without enabling deferred actions",async({page})=>{await setup(page);await page.goto("/transfers");await expect(page.getByRole("button",{name:"Open request TRF_SYNTH_BANK",exact:true})).toBeVisible();await expect(page.getByText("Awaiting ledger confirmation",{exact:true})).toBeVisible();await expect(page.getByRole("heading",{name:"Start local release",exact:true})).toBeVisible();await page.getByRole("tab",{name:"Transfers 1",exact:true}).click();await expect(page.getByRole("button",{name:"Open reservation RES_SYNTH_BANK",exact:true})).toBeVisible();await expect(page.getByRole("button",{name:"Open request TRF_SYNTH_BANK",exact:true})).toHaveCount(0);await page.getByLabel("Search transfers",{exact:true}).fill("missing");await expect(page.getByText("No transfers match your filters",{exact:true})).toBeVisible();await page.getByRole("tab",{name:"Blood Requests 1",exact:true}).click();await expect(page.getByLabel("Search requests",{exact:true})).toHaveValue("");await page.locator(".bank-workflow-availability summary").click();await expect(page.getByText("Canonical reservation actions unavailable",{exact:true})).toBeVisible();await expect(page.getByRole("button",{name:"Dispatch",exact:true})).toHaveCount(0);await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);});
test("activity type and search combine over permitted records",async({page})=>{await setup(page);await page.goto("/audit");await expect(page.locator(".audit-table tbody tr")).toHaveCount(2);await expect(page.getByText(/permitted records/)).toHaveCount(0);await expect(page.locator(".activity-history-page>.page-head").getByRole("button",{name:"Refresh",exact:true})).toBeVisible();expect(await page.locator(".audit-summary").evaluate(el=>{const record=document.querySelector(".blood-bank-audit>.bank-record-card")!.getBoundingClientRect(),first=el.firstElementChild!.getBoundingClientRect(),last=el.lastElementChild!.getBoundingClientRect();return Math.abs(first.left-record.left)<1&&Math.abs(last.right-record.right)<1;})).toBe(true);await page.getByLabel("Activity type",{exact:true}).selectOption("LOCAL_RELEASE");await expect(page.locator(".audit-table tbody tr")).toHaveCount(1);await expect(page.locator(".audit-table tbody tr")).toContainText("FAILED");await page.getByLabel("Search activity",{exact:true}).fill("TX_SYNTH_INTAKE");await expect(page.getByText("No activity matches your filters",{exact:true})).toBeVisible();await page.getByLabel("Activity type",{exact:true}).selectOption("ALL");await expect(page.locator(".audit-table tbody tr")).toHaveCount(1);await expect(page.locator(".audit-table tbody tr")).toContainText("INTAKE COMMITTED");await expect(page.getByRole("button",{name:"Activity History page information",exact:true})).toBeVisible();await expect(page.getByRole("button",{name:"Refresh",exact:true})).toBeVisible();await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);});

test("inventory exports only the selected snapshot and keeps CSV import unavailable",async({page})=>{await setup(page);await page.goto("/inventory");await expect(page.getByRole("button",{name:"Import CSV",exact:true})).toBeDisabled();await expect(page.getByRole("link",{name:"Blood Unit Transactions",exact:true}).last()).toHaveAttribute("href","/transactions");await page.getByLabel("Blood type filter",{exact:true}).selectOption("O_NEGATIVE");const pending=page.waitForEvent("download");await page.getByRole("button",{name:"Export PDF",exact:true}).click();const download=await pending;expect(download.suggestedFilename()).toBe("blood-inventory.pdf");const bytes=await readFile((await download.path())!);const pdf=bytes.toString("latin1");expect(pdf.startsWith("%PDF-")).toBe(true);expect(pdf).toContain("COMP_SYNTH_PRBC");expect(pdf).not.toContain("COMP_SYNTH_PLATELET");expect(pdf).not.toContain("DON_SYNTH_BANK");});
test("separate transactions hub filters activity, exports PDF and opens a phone capture frame",async({page})=>{await setup(page);await page.route("**/api/v2/audit",route=>route.fulfill({contentType:"application/json",body:JSON.stringify({scope:"INSTITUTION",classification:"SIMULATION_ONLY",events:[{auditEventId:"AUD_SYNTH_INBOUND",institutionDisplayName:"Synthetic Mediatrix",actionCode:"REGISTER_INBOUND_COMPONENT",targetType:"COMPONENT",outcome:"COMMITTED",safeErrorCode:null,correlationId:"CORR_SYNTH_INBOUND",ledgerTransactionId:"TX_SYNTH_INBOUND",eventTime:"2026-10-10T00:00:00Z"},{auditEventId:"AUD_SYNTH_OUTBOUND",institutionDisplayName:"Synthetic Mediatrix",actionCode:"DISPATCH_RESERVATION",targetType:"TRANSFER",outcome:"COMMITTED",safeErrorCode:null,correlationId:"CORR_SYNTH_OUTBOUND",ledgerTransactionId:"TX_SYNTH_OUTBOUND",eventTime:"2026-10-10T01:00:00Z"}]})}));await page.goto("/transactions");await expect(page.getByRole("heading",{name:"Recent Blood Unit Transactions",exact:true})).toBeVisible();await expect(page.locator(".transaction-history-table tbody tr")).toHaveCount(2);await page.getByLabel("Direction",{exact:true}).selectOption("Inbound");await expect(page.locator(".transaction-history-table tbody tr")).toHaveCount(1);const pending=page.waitForEvent("download");await page.getByRole("button",{name:"Export PDF",exact:true}).click();const download=await pending;const pdf=(await readFile((await download.path())!)).toString("latin1");expect(download.suggestedFilename()).toBe("blood-unit-transactions.pdf");expect(pdf).toContain("TX_SYNTH_INBOUND");expect(pdf).not.toContain("TX_SYNTH_OUTBOUND");await page.getByRole("button",{name:"Open Mobile Scanner",exact:true}).click();await expect(page.getByRole("dialog",{name:"Mobile blood unit scanner",exact:true})).toBeVisible();await expect(page.locator(".bank-scanner-phone iframe")).toHaveAttribute("src","/capture/?layout=receipt");await page.getByRole("button",{name:"Close mobile scanner",exact:true}).click();await expect(page.getByRole("dialog")).toHaveCount(0);await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);});
test("blood bank dashboard adds requests and honest network availability with request prefill",async({page})=>{await setup(page);await page.goto("/");await expect(page.getByRole("heading",{name:"Requests",exact:true})).toBeVisible();await expect(page.getByRole("heading",{name:"Network Blood Availability",exact:true})).toBeVisible();await expect(page.getByText("Availability unavailable",{exact:true})).toBeVisible();expect(await page.locator(".inventory-overview-card").evaluate(el=>Boolean(el.compareDocumentPosition(document.querySelector(".requester-dashboard-grid")!)&Node.DOCUMENT_POSITION_FOLLOWING))).toBe(true);await page.getByLabel("Blood Type",{exact:true}).selectOption("B_NEGATIVE");await page.getByLabel("Component",{exact:true}).selectOption("PLATELETS");await page.getByRole("link",{name:"+ Request Blood",exact:true}).click();await expect(page.locator(".v2-operation-card").first().getByLabel("Blood type",{exact:true})).toHaveValue("B_NEGATIVE");await expect(page.locator(".v2-operation-card").first().getByLabel("Component")).toHaveValue("PLATELETS");await expect(page.getByRole("button",{name:"Cancel",exact:true})).toBeVisible();await page.getByRole("button",{name:"Cancel",exact:true}).click();await expect(page.getByRole("button",{name:"Submit V2 request",exact:true})).toHaveCount(0);await page.getByRole("button",{name:"+ New Blood Request",exact:true}).click();await expect(page.getByRole("button",{name:"Submit V2 request",exact:true})).toBeVisible();await expect(page.getByRole("tab",{name:"PRC Supply Requests",exact:false})).toBeVisible();});

test("bank dashboard failure preserves card order and recovers with retry",async({page})=>{
 await setup(page);let fail=true;
 await page.route("**/api/v2/dashboard",route=>route.fulfill({status:fail?503:200,contentType:"application/json",body:JSON.stringify(fail?{error:{message:"The dashboard service could not be reached. "+"Unavailable ".repeat(40)}}:{composition:"OPERATIONAL",scope:"INSTITUTION",inventory:[{institutionId:"INST_MEDIATRIX",bloodType:"O_POSITIVE",component:"PACKED_RED_BLOOD_CELLS",inventoryStatus:"AVAILABLE",confirmedCount:3,lastProjectedAt:"2026-10-10T00:00:00Z"}],pendingScans:[],lastSuccessfulProjectionAt:"2026-10-10T00:00:00Z",classification:"SIMULATION_ONLY"})}));
 await page.goto("/");await expect(page.getByText("Unable to load dashboard data",{exact:true})).toBeVisible();await expect(page.getByText("Inventory overview unavailable",{exact:true})).toBeVisible();await expect(page.getByRole("heading",{name:"Requests",exact:true})).toBeVisible();await expect(page.getByRole("heading",{name:"Network Blood Availability",exact:true})).toBeVisible();await expect(page.locator(".dashboard-stats article").first()).toContainText("—");
 expect(await page.locator(".inventory-overview-card").evaluate(el=>Boolean(el.compareDocumentPosition(document.querySelector(".requester-dashboard-grid")!)&Node.DOCUMENT_POSITION_FOLLOWING))).toBe(true);
 await page.setViewportSize({width:390,height:844});await page.getByText("View details",{exact:true}).click();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 fail=false;await page.getByRole("button",{name:"Retry",exact:true}).click();await expect(page.locator(".inventory-overview-chart")).toBeVisible();await expect(page.getByText("Unable to load dashboard data",{exact:true})).toHaveCount(0);await expect(page.locator(".dashboard-stats article").first()).toContainText("3");
 fail=true;await page.getByRole("button",{name:"Refresh",exact:true}).click();await expect(page.getByText("Dashboard could not refresh",{exact:true})).toBeVisible();await expect(page.locator(".inventory-overview-chart")).toBeVisible();await expect(page.locator(".dashboard-stats article").first()).toContainText("3");
});

test("bank receipt-style scanner offers outbound preview and clears drafts on direction change",async({page})=>{
 let posts=0;page.on("request",request=>{if(request.method()==="POST")posts++;});await setup(page);await page.goto("/transactions");await page.getByRole("button",{name:"Open Mobile Scanner",exact:true}).click();const dialog=page.getByRole("dialog",{name:"Mobile blood unit scanner",exact:true});await expect(dialog.locator(".receipt-scanner-content")).toBeVisible();await expect(dialog.getByRole("tab",{name:"Inbound",exact:true})).toHaveAttribute("aria-selected","true");await dialog.getByRole("tab",{name:"Outbound",exact:true}).click();await expect(dialog.getByRole("heading",{name:"Outbound Blood Unit Input",exact:true})).toBeVisible();await expect(dialog.getByRole("button",{name:"Confirm outbound transaction",exact:true})).toBeDisabled();await dialog.getByRole("tab",{name:"Scan",exact:true}).focus();await page.keyboard.press("ArrowRight");await expect(dialog.getByRole("tab",{name:"Manual",exact:true})).toBeFocused();const form=dialog.getByRole("form",{name:"Manual blood unit entry",exact:true});await form.getByLabel("Unit ID",{exact:true}).fill("SYNTHETIC-OUTBOUND-PREVIEW");await form.getByLabel("Expiration Date",{exact:true}).fill("2026-12-10");await expect(form.getByLabel("Destination Facility",{exact:true})).toBeVisible();await form.getByRole("button",{name:"Preview Entry",exact:true}).click();await expect(dialog.getByRole("heading",{name:"Outbound Preview",exact:true})).toBeVisible();await dialog.getByRole("tab",{name:"Scan",exact:true}).click();await dialog.getByLabel("Outbound blood-unit label image").setInputFiles({name:"label.png",mimeType:"image/png",buffer:Buffer.from("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jB1kAAAAASUVORK5CYII=","base64")});await expect(dialog.getByAltText("Selected outbound label preview")).toBeVisible();await dialog.getByRole("tab",{name:"Inbound",exact:true}).click();await dialog.getByRole("tab",{name:"Outbound",exact:true}).click();await expect(dialog.getByAltText("Selected outbound label preview")).toHaveCount(0);await dialog.getByRole("tab",{name:"Manual",exact:true}).click();await expect(form.getByLabel("Unit ID",{exact:true})).toHaveValue("");expect(posts).toBe(0);await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.keyboard.press("Escape");await expect(dialog).toHaveCount(0);await expect(page.getByRole("button",{name:"Open Mobile Scanner",exact:true})).toBeFocused();
});


test("bank row selection reads details and exposes pending decisions without posting",async({page})=>{
 let posts=0;page.on("request",request=>{if(request.method()==="POST")posts++;});await setup(page);await page.goto("/transfers");
 await page.locator(".bank-blood-requests-table tbody tr").getByText("PRBC",{exact:true}).click();
 const detail=page.locator(".bank-detail-card");await expect(detail.getByRole("heading",{name:"Request details",exact:true})).toBeVisible();
 await expect(detail.getByText("Requested units",{exact:true})).toBeVisible();await expect(detail.getByText("Blood type",{exact:true})).toBeVisible();
 for(const name of ["Cancel Request","Offer Available Units","Approve Transfer"])await expect(detail.getByRole("button",{name,exact:true})).toBeDisabled();
 await detail.getByRole("button",{name:"View linked transfer",exact:true}).click();await expect(detail.getByRole("heading",{name:"Transfer details",exact:true})).toBeVisible();await expect(detail.getByText("Preparation evidence",{exact:true})).toBeVisible();await expect(detail.getByRole("button",{name:"Record Outbound Scan",exact:true})).toBeDisabled();
 await page.getByRole("tab",{name:"Transfers 1",exact:true}).click();await page.locator(".bank-record-card tbody tr").getByText("PREPARED",{exact:true}).click();await expect(detail.getByRole("heading",{name:"Transfer details",exact:true})).toBeVisible();
 await page.getByRole("tab",{name:/PRC Supply Requests/}).click();await expect(page.getByLabel("Search transfers",{exact:true})).toHaveCount(0);await page.getByRole("button",{name:"+ Request PRC Supply",exact:true}).click();
 const form=page.getByRole("region",{name:"New PRC Supply Request",exact:true});await expect(form.getByLabel("Required Date & Time",{exact:true})).toBeDisabled();await expect(form.getByRole("button",{name:"Send to PRC Lipa",exact:true})).toBeDisabled();await form.getByRole("button",{name:"Cancel",exact:true}).click();await expect(form).toHaveCount(0);expect(posts).toBe(0);
 await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});

test("bank inbound reservation shows receipt action only after a scoped read",async({page})=>{
 await setup(page);await page.route("**/api/v2/reservations/RES_SYNTH_BANK",route=>route.fulfill({contentType:"application/json",body:JSON.stringify({reservationId:"RES_SYNTH_BANK",purpose:"TRANSFER",status:"IN_TRANSIT",version:3,sourceInstitutionId:"INST_SYNTH_METROLIPA",destinationInstitutionId:"INST_MEDIATRIX",transferId:"TRF_SYNTH_BANK",localReleaseId:null,preparedAt:null,preparedEvidencePresent:false,updatedAt:"2026-10-10T00:00:00Z",components:[],classification:"SIMULATION_ONLY"})}));
 await page.goto("/transfers");await page.getByRole("tab",{name:"Transfers 1",exact:true}).click();await page.getByRole("button",{name:"Open reservation RES_SYNTH_BANK",exact:true}).click();await expect(page.getByRole("button",{name:"Confirm Inbound Receipt",exact:true})).toBeDisabled();await expect(page.getByRole("button",{name:"Record Outbound Scan",exact:true})).toHaveCount(0);
 await page.route("**/api/v2/reservations/RES_SYNTH_BANK",route=>route.fulfill({status:403,contentType:"application/json",body:JSON.stringify({error:{message:"Out of scope"}})}));await page.getByRole("button",{name:"Close record details",exact:true}).click();await page.getByRole("button",{name:"Open reservation RES_SYNTH_BANK",exact:true}).click();await expect(page.getByText("Access denied. This record is outside the authorized scope.",{exact:true})).toBeVisible();await expect(page.getByRole("button",{name:"Confirm Inbound Receipt",exact:true})).toHaveCount(0);
});
