// FR-12: preserve institution scope, permission-based actions and bound retry keys.
import {test,expect,type Page} from "@playwright/test";
const institution={institution_id:"INST_SYNTH_PROFILE_TEST",display_name:"Synthetic Profile Test",account_category:"REQUESTOR",status:"ACTIVE",version:4};
const operators=[{operator_id:"OP_ADMIN_TEST",role_id:"ROLE-06",capability_profile:"INSTITUTION_ADMIN",status:"ACTIVE",version:2},{operator_id:"OP_REQUESTER_TEST",role_id:"ROLE-03",capability_profile:"ROLE",status:"ACTIVE",version:3},{operator_id:"OP_REVOKED_TEST",role_id:"ROLE-03",capability_profile:"ROLE",status:"REVOKED",version:5}];
async function setup(page:Page,admin=true,posts:Array<{path:string;body:Record<string,unknown>;key:string}>=[]){await page.route("**/api/**",async route=>{const req=route.request(),path=new URL(req.url()).pathname;let status=200,body:unknown;
if(path==="/api/v1/auth/session")body={principal:{userId:"USR_TEST",accountId:"ACC_TEST",accountCategory:"REQUESTOR",accountState:"ACTIVE",displayName:"Synthetic Institution Account",institutionId:institution.institution_id,institutionDisplayName:institution.display_name,roleId:"ROLE-03",roleDisplayName:"Institution account",permissions:["dashboard:operational","profile:read","transfers:read"],operators:admin?[{...operators[0],operatorId:"OP_ADMIN_TEST",roleId:"ROLE-06",capabilityProfile:"INSTITUTION_ADMIN",actionCapabilities:["institution:profile","operator:reset-pin"]}]:[],classification:"SIMULATION_ONLY"}};
else if(req.method()==="POST"){posts.push({path,body:req.postDataJSON(),key:req.headers()["idempotency-key"]});status=posts.length===1?503:200;body=status===503?{error:{message:"Synthetic retry failure"}}:{classification:"SIMULATION_ONLY"};}
else if(path==="/api/v2/onboarding/institutions/"+institution.institution_id)body={institution,operators,scope:"INSTITUTION",classification:"SIMULATION_ONLY"};else{status=404;body={error:{message:"Unavailable fixture"}};}await route.fulfill({status,contentType:"application/json",body:JSON.stringify(body)});});}
test("profile has institution fields and own edit, without staff or PRC directory",async({page})=>{const reads:string[]=[];page.on("request",r=>reads.push(new URL(r.url()).pathname));await setup(page);await page.goto("/profile");await expect(page.getByRole("heading",{name:"Facility information",exact:true})).toBeVisible();await expect(page.getByRole("heading",{name:"Authorized operators",exact:true})).toHaveCount(0);for(const name of ["Licensing & qualification","Credentials & access","Application record","Security"])await expect(page.getByRole("heading",{name,exact:true})).toBeVisible();await expect(page.getByRole("button",{name:"Change password",exact:true})).toBeDisabled();await expect(page.getByRole("button",{name:"Reset PIN",exact:true})).toHaveCount(0);await expect(page.getByRole("button",{name:"Edit profile",exact:true})).toBeVisible();await page.getByRole("button",{name:"Edit profile",exact:true}).click();await expect(page.getByLabel("Institution display name")).toBeVisible();expect(reads).not.toContain("/api/v2/onboarding/institutions");expect(reads).not.toContain("/api/v2/onboarding/applications");await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);});
test("accounts filters actual operators and preserves version/idempotency on PIN retry",async({page})=>{const posts:Array<{path:string;body:Record<string,unknown>;key:string}>=[];await setup(page,true,posts);await page.goto("/accounts");await expect(page.getByRole("heading",{name:"Authorized operators",exact:true})).toBeVisible();await expect(page.getByRole("heading",{name:"Facility information",exact:true})).toHaveCount(0);await expect(page.getByRole("button",{name:"Edit profile",exact:true})).toHaveCount(0);await expect(page.getByRole("button",{name:"+ Add administrator",exact:true})).toBeVisible();await page.getByLabel("Operator status",{exact:true}).selectOption("REVOKED");await expect(page.getByRole("button",{name:"Reset PIN",exact:true})).toHaveCount(0);await expect(page.getByText("OP_REVOKED_TEST",{exact:true})).toBeVisible();await page.getByLabel("Operator status",{exact:true}).selectOption("ALL");await page.getByLabel("Find operator",{exact:true}).fill("OP_ADMIN_TEST");await expect(page.getByText("OP_REQUESTER_TEST",{exact:true})).toHaveCount(0);await page.getByRole("button",{name:"Reset PIN",exact:true}).click();await page.getByLabel("Reason code",{exact:true}).fill("SYNTHETIC_TEST");await page.getByLabel("New operator PIN",{exact:true}).fill("13572468");await page.getByRole("button",{name:"Verify and submit change",exact:true}).click();await expect(page.getByRole("status")).toContainText("Synthetic retry failure");await page.getByRole("button",{name:"Verify and submit change",exact:true}).click();await expect(page.getByRole("status")).toContainText("Change recorded");expect(posts).toHaveLength(2);expect(posts[0]).toEqual(posts[1]);expect(posts[0].body.expectedVersion).toBe(2);expect(posts[0].path).toBe("/api/v2/onboarding/operators/OP_ADMIN_TEST/reset-pin");await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);});
test("read-only institution profile exposes no management buttons",async({page})=>{await setup(page,false);await page.goto("/profile");await expect(page.getByRole("heading",{name:"Facility information",exact:true})).toBeVisible();await expect(page.getByRole("button",{name:"Edit profile",exact:true})).toHaveCount(0);await expect(page.getByRole("link",{name:"Staff Accounts",exact:true})).toHaveCount(0);});
