import {test,expect} from "@playwright/test";
for(const category of ["PRC","DOH"]){
 test(`${category} network alerts use shared cards and retain aggregate-only data`,async({page})=>{
  let posts=0;page.on("request",request=>{if(request.method()==="POST")posts++;});
  await page.route("**/api/**",route=>{const path=new URL(route.request().url()).pathname;const body=path==="/api/v1/auth/session"?{principal:{accountId:"ACC_SYNTH_"+category,accountCategory:category,userId:"USR_SYNTH_"+category,displayName:"Synthetic reviewer",institutionId:"INST_SYNTH_"+category,institutionDisplayName:"Synthetic "+category,roleId:"ROLE-04",roleDisplayName:"Reviewer",permissions:["alerts:read"],classification:"SIMULATION_ONLY"}}:path==="/api/v2/alerts"?{scope:"CITY_AGGREGATE",alerts:[],aggregates:[{institutionDisplayName:"Synthetic Blood Bank A",alertType:"EXPIRED",severity:"CRITICAL",status:"OPEN",count:4,lastEvaluatedAt:"2026-10-10T00:00:00Z"},{institutionDisplayName:"Synthetic Blood Bank B",alertType:"STALE_INVENTORY",severity:"WARNING",status:"OPEN",count:2,lastEvaluatedAt:"2026-10-10T00:00:00Z"},{institutionDisplayName:"Synthetic Blood Bank A",alertType:"INVENTORY_UPDATED",severity:"INFORMATION",status:"ACKNOWLEDGED",count:1,lastEvaluatedAt:"2026-10-10T00:00:00Z"}],classification:"SIMULATION_ONLY"}:{error:{message:"Unavailable fixture"}};return route.fulfill({status:["/api/v1/auth/session","/api/v2/alerts"].includes(path)?200:404,contentType:"application/json",body:JSON.stringify(body)});});
  await page.goto("/alerts");await expect(page.locator(".alert-card")).toHaveCount(3);await expect(page.locator(".alert-card.severity-critical")).toContainText("Synthetic Blood Bank A");await expect(page.locator(".alert-card.severity-critical .alert-meta")).toContainText("4");await expect(page.locator(".alert-card.severity-critical .alert-meta")).toContainText("OPEN");await expect(page.getByRole("table")).toHaveCount(0);await expect(page.getByRole("button",{name:"Acknowledge",exact:true})).toHaveCount(0);
  await page.getByRole("button",{name:"Warnings 1",exact:true}).click();await expect(page.locator(".alert-card")).toHaveCount(1);await expect(page.locator(".alert-card")).toContainText("Synthetic Blood Bank B");await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);expect(posts).toBe(0);
 });
}
