import assert from 'node:assert/strict';
import test from 'node:test';
import { runHistoricalCommand } from '../../scripts/historical-inventory/worker.mjs';
import { HistoricalFailure } from '../../scripts/historical-inventory/ledger.mjs';
import { approval, argumentsOf } from '../../scripts/historical-inventory/cli.mjs';
function fixture() {
  const command={command_id:'test',operation:'RegisterUnit',payload:{},snapshot_id:'snapshot',status:'QUEUED',transaction_id:null};
  const calls=[];let onLedger=false,projectionFails=false,queryFails=false,submitTimeout=false;
  const evidence={transactionId:'a'.repeat(64),blockNumber:'9007199254740993',validationStatus:'VALID',asset:{}};
  const store={next:async()=>command.status==='COMMITTED'?null:command,saveSubmission:async(id,tx,bytes)=>{Object.assign(command,{transaction_id:tx,signed_transaction:bytes,status:'SUBMITTING'});calls.push('saved-before-submit');},saveCommit:async(id,result)=>{Object.assign(command,{status:'LEDGER_COMMITTED_PROJECTION_PENDING',ledger_result:result.asset,block_number:result.blockNumber,validation_status:'VALID'});calls.push('saved-commit');},project:async()=>{calls.push('project');if(projectionFails)throw new Error('db temporarily unavailable');command.status='COMMITTED';},fail:async(id,code)=>{command.status='FAILED';command.safe_error_code=code;}};
  const ledger={prepare:async()=>{calls.push('prepare');return {transactionId:evidence.transactionId,bytes:Buffer.from('saved envelope')};},inspect:async()=>{calls.push('inspect');if(queryFails)throw new HistoricalFailure('HISTORICAL_LEDGER_QUERY_UNAVAILABLE');return onLedger?evidence:null;},submitSaved:async()=>{assert.ok(command.signed_transaction);calls.push('submit');onLedger=true;if(submitTimeout)throw new HistoricalFailure('HISTORICAL_SUBMISSION_UNKNOWN');}};
  return {command,calls,store,ledger,evidence,setProjectionFail:v=>projectionFails=v,setQueryFail:v=>queryFails=v,setTimeout:v=>submitTimeout=v};
}
test('FR-13 saves envelope before submit and projects a valid commit',async()=>{const f=fixture();await runHistoricalCommand(f.store,f.ledger,'snapshot');assert.equal(f.command.status,'COMMITTED');assert.ok(f.calls.indexOf('saved-before-submit')<f.calls.indexOf('submit'));assert.equal(await runHistoricalCommand(f.store,f.ledger,'snapshot'),'COMPLETE');});
test('FR-13 commit before projection restart retries projection without a ledger call',async()=>{const f=fixture();f.setProjectionFail(true);await assert.rejects(runHistoricalCommand(f.store,f.ledger,'snapshot'));assert.equal(f.command.status,'LEDGER_COMMITTED_PROJECTION_PENDING');const before=f.calls.length;f.setProjectionFail(false);await runHistoricalCommand(f.store,f.ledger,'snapshot');assert.deepEqual(f.calls.slice(before),['project']);});
test('FR-13 ambiguous commit resolves from ledger without another proposal or submission',async()=>{const f=fixture();f.setTimeout(true);await assert.rejects(runHistoricalCommand(f.store,f.ledger,'snapshot'));assert.equal(f.command.status,'SUBMITTING');await runHistoricalCommand(f.store,f.ledger,'snapshot');assert.equal(f.calls.filter(c=>c==='prepare').length,1);assert.equal(f.calls.filter(c=>c==='submit').length,1);});
test('FR-13 unavailable peer prevents blind resubmit; reconnect reuses envelope',async()=>{const f=fixture();f.setQueryFail(true);await assert.rejects(runHistoricalCommand(f.store,f.ledger,'snapshot'));assert.equal(f.calls.filter(c=>c==='submit').length,0);f.setQueryFail(false);await runHistoricalCommand(f.store,f.ledger,'snapshot');assert.equal(f.calls.filter(c=>c==='prepare').length,1);});
test('FR-13 invalid ledger result becomes terminal and is never projected',async()=>{const f=fixture();f.ledger.inspect=async()=>{throw new HistoricalFailure('HISTORICAL_TRANSACTION_INVALID',true);};await assert.rejects(runHistoricalCommand(f.store,f.ledger,'snapshot'));assert.equal(f.command.status,'FAILED');assert.equal(f.calls.filter(c=>c==='project').length,0);});
test('FR-14 explicit hash, source review, authorized actor and local target are required',()=>{const manifest={manifestSha256:'a'.repeat(64)};const valid={target:'bloodledger-local','approve-manifest':manifest.manifestSha256,operator:'USR_SYNTH_HISTORICAL_IMPORT','review-reference':'Buno reviewed synthetic fixture'};approval(valid,manifest);for(const key of Object.keys(valid))assert.throws(()=>approval({...valid,[key]:''},manifest));assert.equal(argumentsOf(['--output','build/test.json']).command,'preview');assert.throws(()=>argumentsOf(['apply','--unknown','x']));assert.throws(()=>argumentsOf(['apply','--output','x','--output','y']));});
