import { useState, type ReactNode } from "react";
import type { Principal } from "../../auth/permissions";
import { PreviewModal } from "../../components/ui/preview-modal";

const tabs = ["Overview", "Applications", "Institutions", "User accounts", "Roles & capabilities", "Activity"] as const;
type Tab = typeof tabs[number];
type PreviewKind = "application" | "institution" | "user" | undefined;
const applications = [{ reference: "APP-SYNTH-0001", institution: "Synthetic Blood Bank Alpha", type: "Blood Bank", classification: "Level 3 Hospital", status: "Pending review" },{ reference: "APP-SYNTH-0002", institution: "Synthetic Requestor Beta", type: "Requestor", classification: "Level 2 Hospital", status: "Needs verification" }];
const institutions = [{ reference: "INST-SYNTH-ALPHA", name: "Synthetic Blood Bank Alpha", type: "Blood Bank", users: 2, status: "Preview active" },{ reference: "INST-SYNTH-BETA", name: "Synthetic Requestor Beta", type: "Requestor", users: 1, status: "Preview pending" },{ reference: "INST-SYNTH-REG", name: "Synthetic Regulatory Office", type: "Regulatory", users: 1, status: "Preview active" }];
const users = [
  { reference: "USR-SYNTH-ROLE01", label: "Synthetic Medical Technologist", institution: "Synthetic Mediatrix Hospital", role: "Medical Technologist", roleId: "ROLE-01", status: "Demonstration only" },
  { reference: "USR-SYNTH-ROLE02", label: "Synthetic Hospital Administrator", institution: "Synthetic Mediatrix Hospital", role: "Hospital Administrator", roleId: "ROLE-02", status: "Demonstration only" },
  { reference: "USR-SYNTH-ROLE03", label: "Synthetic Secondary Hospital User", institution: "Synthetic Secondary Hospital", role: "Secondary Hospital User", roleId: "ROLE-03", status: "Demonstration only" },
  { reference: "USR-SYNTH-ROLE04", label: "Synthetic Regulatory Viewer", institution: "Synthetic Regulatory Office", role: "DOH/PRC Regulatory Viewer", roleId: "ROLE-04", status: "Demonstration only" },
  { reference: "USR-SYNTH-ROLE05", label: "Synthetic System Administrator", institution: "Synthetic System Scope", role: "System Administrator", roleId: "ROLE-05", status: "Demonstration only" },
  { reference: "USR-SYNTH-ROLE06", label: "Synthetic Institution Account Administrator", institution: "Synthetic Account Institution", role: "Institution Account Administrator", roleId: "ROLE-06", status: "Demonstration only" },
];
const roles = [
  { id: "ROLE-01", name: "Medical Technologist", scope: "Institution operations", capabilities: ["View and register local inventory", "Confirm dispatch and local receipt", "Acknowledge authorized alerts"], limitation: "Cannot approve outgoing transfers." },
  { id: "ROLE-02", name: "Hospital Administrator", scope: "Supplying institution", capabilities: ["Oversee local inventory", "Submit and decide transfer requests", "Confirm dispatch, receipt, and permitted audit"], limitation: "Cannot perform city-wide regulatory administration." },
  { id: "ROLE-03", name: "Secondary Hospital User", scope: "Recipient institution", capabilities: ["View approved aggregate availability", "Submit blood requests", "Confirm receipt, exception, and permitted delay"], limitation: "Cannot register supplying inventory or approve outgoing transfers." },
  { id: "ROLE-04", name: "DOH/PRC Regulatory Viewer", scope: "Approved city-wide aggregate", capabilities: ["Read aggregate inventory and alerts", "Read transfer and audit history", "Export approved regulatory reports"], limitation: "Read-only; no inventory, custody, transfer, or account mutation." },
  { id: "ROLE-05", name: "System Administrator", scope: "System administration", capabilities: ["Review institutional applications", "Manage users and institutions", "View security and system operations"], limitation: "No clinical, custody, or transfer authority by default." },
  { id: "ROLE-06", name: "Institution Account Administrator", scope: "One activated institution", capabilities: ["Manage own institution profile", "Manage own institution users", "View user/profile administration history"], limitation: "No clinical, custody, transfer, or Fabric authority." },
];
const activity = [{ action: "Application submitted", target: "APP-SYNTH-0001", actor: "Synthetic applicant", outcome: "Preview only" },{ action: "Institution reviewed", target: "INST-SYNTH-ALPHA", actor: "Synthetic administrator", outcome: "No persisted event" }];

function PreviewAction({ children, onClick }: { children: string; onClick: () => void }) { return <button className="button compact" type="button" onClick={onClick}>{children}</button>; }
function Panel({ title, description, action, children }: { title: string; description: string; action?: ReactNode; children: ReactNode }) { return <section className="account-panel"><header><div><h3>{title}</h3><p>{description}</p></div>{action}</header>{children}</section>; }
function RoleCapabilityCatalog() { return <Panel title="Official roles and capabilities" description="All six approved roles from REQUIREMENTS.md Section 2 are represented with their least-privilege boundary."><div className="role-catalog-grid">{roles.map(role => <article className="role-capability-card" key={role.id}><header><span className="mono">{role.id}</span><strong>{role.name}</strong><small>{role.scope}</small></header><ul>{role.capabilities.map(capability => <li key={capability}>{capability}</li>)}</ul><p><b>Boundary:</b> {role.limitation}</p></article>)}</div><div className="role-catalog-note"><span aria-hidden="true">i</span><p>This catalog explains the approved role model. It does not read the local credential file, change a user's role, or prove backend authorization.</p></div></Panel>; }

export function AccountsParityPreview({ principal }: { principal: Principal }) {
  const [tab, setTab] = useState<Tab>("Overview");
  const [preview, setPreview] = useState<PreviewKind>();
  if (!["ROLE-05", "ROLE-06"].includes(principal.roleId)) return <div className="account-empty"><span aria-hidden="true">!</span><strong>Administration preview unavailable</strong><p>This client-side composition is not an API authorization boundary.</p></div>;
  const table = tab === "Applications" ? <Panel title="Institution applications" description="Review, verification, and decisions are visual only." action={<PreviewAction onClick={() => setPreview("application")}>Open review dialog</PreviewAction>}><div className="table-wrap"><table className="data-table"><thead><tr><th>Application</th><th>Institution</th><th>Type</th><th>Classification</th><th>Status</th><th/></tr></thead><tbody>{applications.map(item => <tr key={item.reference}><td className="mono">{item.reference}</td><td><strong>{item.institution}</strong></td><td>{item.type}</td><td>{item.classification}</td><td><span className="status warning">{item.status}</span></td><td><PreviewAction onClick={() => setPreview("application")}>Review</PreviewAction></td></tr>)}</tbody></table></div></Panel>
    : tab === "Institutions" ? <Panel title="Consortium institutions" description="Activation, suspension, and membership changes are unavailable." action={<PreviewAction onClick={() => setPreview("institution")}>Add institution</PreviewAction>}><div className="table-wrap"><table className="data-table"><thead><tr><th>Institution</th><th>Reference</th><th>Participation</th><th>Users</th><th>Status</th><th/></tr></thead><tbody>{institutions.map(item => <tr key={item.reference}><td><strong>{item.name}</strong></td><td className="mono">{item.reference}</td><td>{item.type}</td><td>{item.users}</td><td><span className="status">{item.status}</span></td><td><PreviewAction onClick={() => setPreview("institution")}>View</PreviewAction></td></tr>)}</tbody></table></div></Panel>
    : tab === "User accounts" ? <Panel title="Authorized user accounts" description="Provisioning, roles, suspension, recovery, and deletion are unavailable." action={<PreviewAction onClick={() => setPreview("user")}>Provision account</PreviewAction>}><div className="account-toolbar-preview"><label>Search accounts<input placeholder="Search synthetic accounts..." /></label><span>{users.length} preview rows</span></div><div className="table-wrap"><table className="data-table"><thead><tr><th>User</th><th>Institution</th><th>Role</th><th>Role ID</th><th>Reference</th><th>Status</th><th/></tr></thead><tbody>{users.map(item => <tr key={item.reference}><td><strong>{item.label}</strong></td><td>{item.institution}</td><td>{item.role}</td><td className="mono">{item.roleId}</td><td className="mono">{item.reference}</td><td><span className="status">{item.status}</span></td><td><PreviewAction onClick={() => setPreview("user")}>Manage</PreviewAction></td></tr>)}</tbody></table></div></Panel>
    : tab === "Roles & capabilities" ? <RoleCapabilityCatalog />
    : tab === "Activity" ? <Panel title="Administration activity" description="Rows illustrate the audit-table appearance and are not recorded events."><div className="table-wrap"><table className="data-table"><thead><tr><th>Action</th><th>Target</th><th>Actor</th><th>Outcome</th></tr></thead><tbody>{activity.map(item => <tr key={item.target}><td><strong>{item.action}</strong></td><td className="mono">{item.target}</td><td>{item.actor}</td><td><span className="status warning">{item.outcome}</span></td></tr>)}</tbody></table></div></Panel>
    : <><div className="account-summary"><article><span>Applications</span><strong>2</strong><small>Synthetic preview rows</small></article><article><span>Institutions</span><strong>3</strong><small>Visual examples</small></article><article><span>User accounts</span><strong>{users.length}</strong><small>All official roles represented</small></article><article><span>Activity</span><strong>2</strong><small>Non-persisted examples</small></article></div><Panel title="Application review queue" description="Mockup-derived administrative overview with non-persistent examples." action={<PreviewAction onClick={() => setTab("Applications")}>View all</PreviewAction>}><div className="table-wrap"><table className="data-table"><thead><tr><th>Reference</th><th>Institution</th><th>Type</th><th>Status</th><th/></tr></thead><tbody>{applications.map(item => <tr key={item.reference}><td className="mono">{item.reference}</td><td><strong>{item.institution}</strong></td><td>{item.type}</td><td><span className="status warning">{item.status}</span></td><td><PreviewAction onClick={() => setPreview("application")}>Open preview</PreviewAction></td></tr>)}</tbody></table></div></Panel></>;
  return <div className="accounts-preview"><div className="preview-disclosure"><span aria-hidden="true">i</span><div><strong>Visual administration workspace</strong><p>Nothing on this page reads or changes accounts, institutions, applications, licenses, documents, or audit records.</p></div><b>FRONTEND ONLY</b></div><div className="account-tabs" role="tablist" aria-label="Administration sections">{tabs.map(value => <button type="button" role="tab" aria-selected={tab === value} className={tab === value ? "active" : ""} onClick={() => setTab(value)} key={value}>{value}</button>)}</div>{table}
    {preview && <PreviewModal title={preview === "application" ? "Review institutional application" : preview === "institution" ? "Institution details" : "Manage user account"} description="This dialog reproduces the mockup interaction without performing an operation." onClose={() => setPreview(undefined)} footer={<><button className="button" type="button" onClick={() => setPreview(undefined)}>Close</button><button className="button danger" type="button" disabled>{preview === "application" ? "Reject" : "Suspend"}</button><button className="button primary" type="button" disabled>{preview === "application" ? "Approve application" : preview === "institution" ? "Activate institution" : "Save account"}</button></>}><div className="preview-detail-grid"><div><span>Reference</span><strong className="mono">{preview === "application" ? applications[0].reference : preview === "institution" ? institutions[0].reference : users[0].reference}</strong></div><div><span>Runtime state</span><strong>Not connected</strong></div><div><span>Verification</span><strong>Unavailable</strong></div><div><span>Persistence</span><strong>None</strong></div></div><div className="preview-document-list"><strong>Supporting evidence</strong><div><span aria-hidden="true">≡</span><p><b>Document preview unavailable</b><small>No file was uploaded, fetched, or verified.</small></p><span className="status warning">Placeholder</span></div></div></PreviewModal>}
  </div>;
}
