import { InstitutionProfileSections } from "../profile/institution-profile-sections";
import { InformationHelp } from "../../components/ui/information-help";
import { humanizeCode, statusClassName } from "../../components/ui/display";
import { useRef, useState } from "react";
import { canAct, type Principal } from "../../auth/permissions";
import { useLiveData } from "../../hooks/use-live-data";
import { requestJson } from "../../services/api/client";
import { newMutationKeys, type MutationKeys } from "../../services/api/mutation-keys";

interface Institution {institution_id: string; display_name: string; account_category: string; status: string; version: number; username?: string}
interface Operator {operator_id: string; role_id: string; capability_profile: string; status: string; version: number}
interface Application {application_id: string; status: string; version: number; institution_id: string | null; category: string; detail: {institutionDisplayName: string} | null}
type Action = {path: string; title: string; version?: number; fields: string[]; fixed?: Record<string, unknown>};

export function InstitutionAccountsView({principal,mode="accounts"}: {principal: Principal;mode?:"profile"|"accounts"}) {
  const profileMode=mode==="profile";
  const prc = principal.accountCategory === "PRC" && !profileMode;
  const directory = useLiveData<{institutions: Institution[]}>(prc ? "/api/v2/onboarding/institutions" : null);
  const profile = useLiveData<{institution: Institution; operators: Operator[]}>("/api/v2/onboarding/institutions/" + principal.institutionId);
  const applications = useLiveData<{applications: Application[]}>(prc ? "/api/v2/onboarding/applications" : null);
  const [search,setSearch]=useState(""),[operatorStatus,setOperatorStatus]=useState("ALL");
  const [selected, setSelected] = useState<Action>();
  const [values, setValues] = useState<Record<string, string>>({});
  const [message, setMessage] = useState("");
  const [busy, setBusy] = useState(false);
  const attempt = useRef<{keys: MutationKeys; payload: Record<string, unknown>} | undefined>(undefined);
  const institutions = prc ? directory.data?.institutions ?? [] : profile.data ? [profile.data.institution] : [];
  function choose(action: Action) {setSelected(action); setValues({reasonCode:"SYNTHETIC_REVIEW"}); setMessage(""); attempt.current = undefined;}
  async function submit(event: React.FormEvent) {
    event.preventDefault(); if (!selected) return;
    setBusy(true); setMessage("");
    const current = attempt.current ?? (() => {
      const keys = newMutationKeys();
      const payload: Record<string, unknown> = {...Object.fromEntries(selected.fields.map(field => [field, values[field]])), ...selected.fixed, correlationId:keys.correlationId};
      if (selected.version !== undefined) payload.expectedVersion = selected.version;
      return {keys, payload};
    })();
    attempt.current = current;
    try {
      const result = await requestJson<{invitationSecret?: string | null}>(selected.path, {method:"POST",headers:{"Idempotency-Key":current.keys.idempotencyKey},body:JSON.stringify(current.payload)});
      setMessage(result.invitationSecret ? "Invitation secret for private delivery: " + result.invitationSecret : "Change recorded. The server remains authoritative for access.");
      setValues({}); setSelected(undefined); attempt.current = undefined;
      directory.manual(); profile.manual(); applications.manual();
    } catch (reason) {setMessage(reason instanceof Error ? reason.message : "Change failed.");}
    finally {setBusy(false);}
  }
  const admin = principal.accountCategory === "PRC" || canAct(principal,"institution:profile");
  const institution=profile.data?.institution;
  const name=institution?.institution_id==="INST_SYNTH_METROLIPA" && institution.display_name==="Synthetic Metro Lipa" ? "Metro Lipa Medical Center" : institution?.display_name ?? principal.institutionDisplayName;
  const operators=profile.data?.operators;
  const filteredOperators=(operators??[]).filter(operator=>(operatorStatus==="ALL"||operator.status===operatorStatus)&&`${operator.operator_id} ${operator.role_id} ${operator.capability_profile} ${roleName(operator.role_id)}`.toLowerCase().includes(search.trim().toLowerCase()));
  const ownEdit=institution?{path:`/api/v2/onboarding/institutions/${institution.institution_id}/profile`,title:"Edit institution profile",version:institution.version,fields:["displayName"]}:undefined;
  return <section className={profileMode?"institution-profile-view":"institution-accounts-view"}>
    {[directory.error,profile.error,applications.error].filter(Boolean).map((error,i)=><div className="requester-transfer-notice" role="status" key={i}><span className="requester-notice-icon" aria-hidden="true">!</span><div className="requester-notice-copy"><strong>Account information unavailable</strong><p>{error}</p></div><button className="button compact dashboard-refresh" onClick={()=>{directory.manual();profile.manual();applications.manual();}}>Retry</button></div>)}
    {profileMode?<>
      <div className="institution-identity-card"><span className="institution-identity-avatar" aria-hidden="true">{name.split(/\s+/).slice(0,2).map(part=>part[0]).join("")}</span><div><span className="receipt-eyebrow">Institution profile</span><h2>{name}</h2><p>{categoryName(institution?.account_category??principal.accountCategory??"")}</p></div><span className={statusClassName(institution?.status??principal.accountState??"UNKNOWN")}>{humanizeCode(institution?.status??principal.accountState??"Unavailable")}</span></div>
      <div className="institution-profile-grid"><section className="institution-settings-card"><header><h2>Facility information</h2>{admin&&ownEdit&&<button className="button compact" onClick={()=>choose(ownEdit)}>Edit profile</button>}<InformationHelp label="Facility information">Review your institution’s registered identity and participation type. Authorized administrators can update its display name using operator verification.</InformationHelp></header><dl className="institution-field-grid"><ProfileField label="Facility name" value={name}/><ProfileField label="Participation type" value={categoryName(institution?.account_category??principal.accountCategory??"")}/><ProfileField label="Institution ID" value={principal.institutionId}/><ProfileField label="Account status" value={humanizeCode(institution?.status??principal.accountState??"Unavailable")}/><ProfileField label="Registered legal name"/><ProfileField label="Ownership"/><ProfileField label="Facility classification"/><ProfileField label="Complete address"/><ProfileField label="City / Municipality"/><ProfileField label="Province"/></dl></section>
      <section className="institution-settings-card"><header><h2>Official contact</h2><InformationHelp label="Official contact">Official contact details will appear here when supported by the institution profile service.</InformationHelp></header><dl className="institution-field-grid"><ProfileField label="Official email"/><ProfileField label="Official phone"/></dl><p className="institution-section-note">Official contact details are not available in the current profile service.</p></section></div>
      <section className="institution-settings-card institution-access-reference"><header><h2>Facility Account</h2><InformationHelp label="Account information">This is the shared institution account. Manage individual operators, PINs and access in Staff Accounts.</InformationHelp></header><dl className="institution-field-grid"><ProfileField label="Account ID" value={principal.accountId}/><ProfileField label="Account type" value="Institution account"/><ProfileField label="Facility Account email"/><ProfileField label="Account status" value={humanizeCode(institution?.status??principal.accountState??"Unavailable")}/></dl></section>
      <InstitutionProfileSections principal={principal}/>
    </>:<>
    <header className="institution-staff-header"><h1 className="page-title">Staff Accounts</h1>{!prc&&admin&&institution&&["BLOOD_BANK","REQUESTOR"].includes(institution.account_category)&&<button className="button primary compact" onClick={()=>choose({path:"/api/v2/onboarding/operators",title:"Add institution administrator",version:institution.version,fields:["pin"],fixed:{institutionId:institution.institution_id}})}>+ Add administrator</button>}</header>
    <div className="institution-operator-summary">{[["Operators",operators?.length],["Active",operators?.filter(o=>o.status==="ACTIVE").length],["Administrators",operators?.filter(o=>o.capability_profile==="INSTITUTION_ADMIN").length],["Revoked",operators?.filter(o=>o.status==="REVOKED").length]].map(([label,count])=><article key={String(label)}><span>{label}</span><strong>{count??"—"}</strong></article>)}</div>
    {prc && <button className="button" onClick={()=>choose({path:"/api/v2/onboarding/invitations",title:"Issue synthetic invitation",fields:["category"]})}>Issue invitation</button>}
    {prc&&<section className="institution-settings-card"><header><h2>Institution accounts</h2></header><div className="table-wrap"><table className="data-table"><thead><tr><th>Institution</th><th>Category</th><th>Login</th><th>Status</th><th>Actions</th></tr></thead><tbody>{institutions.map(inst=><tr key={inst.institution_id}><td>{inst.display_name}</td><td>{inst.account_category}</td><td>{inst.username ?? "Current institution login"}</td><td>{inst.status}</td><td>
      {admin && <button className="button compact" onClick={()=>choose({path:`/api/v2/onboarding/institutions/${inst.institution_id}/profile`,title:"Edit institution profile",version:inst.version,fields:["displayName"]})}>Edit profile</button>}
      {prc && ["BLOOD_BANK","REQUESTOR"].includes(inst.account_category) && <><button className="button compact" onClick={()=>choose({path:`/api/v2/onboarding/institutions/${inst.institution_id}/${inst.status === "ACTIVE" ? "suspend" : "reactivate"}`,title:inst.status === "ACTIVE" ? "Suspend institution" : "Reactivate institution",version:inst.version,fields:["reasonCode"]})}>{inst.status === "ACTIVE" ? "Suspend" : "Reactivate"}</button><button className="button compact" disabled={inst.status!=="ACTIVE"} onClick={()=>choose({path:`/api/v2/onboarding/institutions/${inst.institution_id}/account`,title:"Replace primary login",version:inst.version,fields:["loginEmail","password"]})}>Replace login</button></>}
      {admin && ["BLOOD_BANK","REQUESTOR"].includes(inst.account_category) && <button className="button compact" onClick={()=>choose({path:"/api/v2/onboarding/operators",title:"Add institution administrator",version:inst.version,fields:["pin"],fixed:{institutionId:inst.institution_id}})}>Add administrator</button>}
    </td></tr>)}</tbody></table></div></section>}
    <section className="institution-settings-card"><header><h2>Authorized operators</h2><InformationHelp label="Authorized operators">Each operator uses an individual PIN to authorize permitted actions. Reset PIN and Revoke remain subject to administrator permissions and operator verification. Revoking access does not remove historical attribution.</InformationHelp></header>
    <div className="institution-operator-filters"><label>Find operator<input type="search" placeholder="Search ID or role" value={search} onChange={event=>setSearch(event.target.value)}/></label><label>Status<span className="requester-select"><select aria-label="Operator status" value={operatorStatus} onChange={event=>setOperatorStatus(event.target.value)}><option value="ALL">All statuses</option>{[...new Set((operators??[]).map(o=>o.status))].sort().map(status=><option key={status} value={status}>{humanizeCode(status)}</option>)}</select></span></label><span>{filteredOperators.length} operators</span></div>
    <div className="table-wrap"><table className="data-table"><thead><tr><th>Operator</th><th>Role</th><th>Access profile</th><th>Status</th><th>Actions</th></tr></thead><tbody>{filteredOperators.map(operator=><tr key={operator.operator_id}><td className="mono">{operator.operator_id}</td><td>{roleName(operator.role_id)}</td><td>{operator.capability_profile==="INSTITUTION_ADMIN"?"Administrator":operator.capability_profile==="ROLE"?"Role permissions":humanizeCode(operator.capability_profile)}</td><td><span className={statusClassName(operator.status)}>{humanizeCode(operator.status)}</span></td><td>{canAct(principal,"operator:reset-pin") && operator.status==="ACTIVE" && <><button className="button compact" onClick={()=>choose({path:`/api/v2/onboarding/operators/${operator.operator_id}/reset-pin`,title:"Reset operator PIN",version:operator.version,fields:["reasonCode","pin"]})}>Reset PIN</button><button className="button compact" onClick={()=>choose({path:`/api/v2/onboarding/operators/${operator.operator_id}/revoke`,title:"Revoke operator",version:operator.version,fields:["reasonCode"]})}>Revoke</button></>}</td></tr>)}</tbody></table></div>
    {!operators?<div className="requester-records-empty"><strong>{profile.error?"Operator list unavailable":"Loading operators…"}</strong></div>:filteredOperators.length===0&&<div className="requester-records-empty"><strong>{operators.length?"No operators match your filters":"No operators recorded"}</strong></div>}</section>
    {prc && <><h3>Institution applications</h3>{applications.data?.applications.length===0 && <p>No applications submitted.</p>}<div className="table-wrap"><table className="data-table"><thead><tr><th>Institution</th><th>Category</th><th>Status</th><th>Actions</th></tr></thead><tbody>{applications.data?.applications.map(app=><tr key={app.application_id}><td>{app.detail?.institutionDisplayName ?? "Retained decision reference"}</td><td>{app.category}</td><td>{app.status}</td><td>{(app.status==="SUBMITTED" ? ["review"] : app.status==="UNDER_REVIEW" ? ["approve","reject"] : app.status==="APPROVED" && !app.institution_id ? ["activate"] : []).map(action=><button className="button compact" key={action} onClick={()=>choose({path:`/api/v2/onboarding/applications/${app.application_id}/${action}`,title:action + " synthetic application",version:app.version,fields:action==="review" ? ["verificationReference"] : action==="activate" ? ["reasonCode","loginEmail","password","operatorPin"] : ["reasonCode"],fixed:action==="review" ? {verificationOutcome:"CONFIRMED"} : undefined})}>{action}</button>)}</td></tr>)}</tbody></table></div></>}
    </>}
    {selected && <section className="v2-operation-card"><h3>{selected.title}</h3><form className={`v2-operation-form${profileMode ? " institution-profile-edit-form" : ""}`} onSubmit={event=>void submit(event)}>{selected.fields.map(field=><label key={field}>{({reasonCode:"Reason code",displayName:"Institution display name",loginEmail:"Institution email",password:"New account password",pin:"New operator PIN",operatorPin:"New administrator PIN",verificationReference:"Synthetic verification reference",category:"Account category"} as Record<string,string>)[field] ?? field}{field==="category" ? <select value={values[field] ?? ""} onChange={event=>{attempt.current=undefined;setValues({...values,[field]:event.target.value});}} required><option value="">Choose category</option><option value="BLOOD_BANK">Blood bank</option><option value="REQUESTOR">Requestor</option></select> : <input type={["pin","password","operatorPin"].includes(field) ? "password" : field==="loginEmail" ? "email" : "text"} value={values[field] ?? ""} autoComplete="off" minLength={field==="password" ? 12 : ["pin","operatorPin"].includes(field) ? 8 : undefined} maxLength={["pin","operatorPin"].includes(field) ? 8 : undefined} onChange={event=>{attempt.current=undefined;setValues({...values,[field]:event.target.value});}} required/>}</label>)}<div className="institution-edit-actions"><button className="button compact" type="button" disabled={busy} onClick={()=>{setSelected(undefined);setValues({});attempt.current=undefined;}}>Cancel</button><button className="button primary compact" disabled={busy}>{busy ? "Waiting for verification…" : "Verify and submit change"}</button></div></form></section>}
    {message && <p role="status">{message}</p>}
  </section>;
}

function categoryName(value:string){return ({REQUESTOR:"Requester facility",BLOOD_BANK:"Blood-bank facility",PRC:"PRC administration",DOH:"DOH regulatory office"} as Record<string,string>)[value]??humanizeCode(value||"Unavailable");}
function roleName(value:string){return ({"ROLE-01":"Medical technologist","ROLE-02":"Hospital administrator","ROLE-03":"Requester operator","ROLE-04":"Regulatory viewer","ROLE-05":"System administrator","ROLE-06":"Institution administrator"} as Record<string,string>)[value]??humanizeCode(value);}
function ProfileField({label,value}:{label:string;value?:string}){return <div><dt>{label}</dt><dd className={value?undefined:"institution-field-unavailable"}>{value??"Not available"}</dd></div>;}
