import type {Principal} from "../../auth/permissions";
import {InformationHelp} from "../../components/ui/information-help";
import {humanizeCode} from "../../components/ui/display";
function Fields({values}:{values:Array<[string,string?]>}){return <dl className="institution-field-grid">{values.map(([label,value])=><div key={label}><dt>{label}</dt><dd className={value?undefined:"institution-field-unavailable"}>{value??"Not available"}</dd></div>)}</dl>;}
export function InstitutionProfileSections({principal}:{principal:Principal}){
 const requester=principal.accountCategory==="REQUESTOR",bank=principal.accountCategory==="BLOOD_BANK";
 const scope=requester?"Requester facility":bank?"Blood-bank facility":principal.accountCategory==="PRC"?"PRC administration":"Regulatory office";
 return <>
 {(bank||requester)&&<section className="institution-settings-card"><header><h2>Licensing & qualification</h2><InformationHelp label="Licensing and qualification">These fields correspond to your application category. License details, expiry dates, qualification records and declarations are not provided by the current institution profile read.</InformationHelp></header><Fields values={[["Hospital / Health Facility LTO"],["LTO expiration"],[bank?"DOH BSF LTO number":"Blood Station ATO / authorization"],["License / authority expiration"],...(bank?[["Blood Service Facility category"],["Head of Blood Service Facility"],["Physician PRC license"]]:[["Referral / supplying facility"]]) as Array<[string,string?]>,["Medical technologist-in-charge"],["Medical technologist PRC license"],["Capability declaration"],["Readiness declaration"],["Verification declaration"]]}/><div className="institution-document-placeholder"><span aria-hidden="true">↥</span><div><strong>Supporting documents</strong><p>Application document references will appear here when available.</p></div><button className="button compact" disabled>View documents</button></div></section>}
 <div className="institution-profile-grid institution-profile-secondary"><section className="institution-settings-card"><header><h2>Credentials & access</h2><InformationHelp label="Credentials and access">Review the role and scope assigned to this account. Individual operators authorize their permitted actions with private PINs; PIN management remains in Staff Accounts.</InformationHelp></header><Fields values={[["Assigned account role",principal.roleDisplayName],["Role reference",principal.roleId],["Access scope",scope],["Facility ID",principal.institutionId],["Last sign-in"]]}/></section>
 <section className="institution-settings-card"><header><h2>Application record</h2><InformationHelp label="Application record">Your institution’s linked application reference and review history will appear here once an authorized own-application read is available. Existing account activation does not establish application dates or reviewer details.</InformationHelp></header><Fields values={[["Application ID"],["Application type",scope],["Application status"],["Submitted"],["Approved"],["Approved by"]]}/></section></div>
 <section className="institution-settings-card"><header><h2>Security</h2><InformationHelp label="Security">Passwords and operator PINs are never displayed or retrievable here. The applicant-status password is separate from the institution login provisioned during activation. Self-service password changes are not connected yet.</InformationHelp></header><div className="institution-security-row"><div><strong>Institution password</strong><p>Keep your login password private. The current account policy requires at least 12 characters.</p></div><button className="button compact" type="button" disabled title="Self-service password change is not connected yet.">Change password</button></div><div className="institution-security-row"><div><strong>Operator authorization</strong><p>Each authorized operator uses a private PIN for permitted actions. Manage operator access in Staff Accounts.</p></div><span className="institution-security-label">{principal.verificationRequired?"Verification required":"Account permissions apply"}</span></div></section>
 </>;
}
