import { useState } from "react";
import type { Principal } from "../../auth/permissions";
import { humanizeCode } from "../../components/ui/display";
import { PreviewModal } from "../../components/ui/preview-modal";

function PlaceholderField({ label, value = "Not available" }: { label: string; value?: string }) { return <div className="profile-preview-field"><span>{label}</span><strong>{value}</strong><small>Requires an approved profile or onboarding contract</small></div>; }

export function ProfileParityPreview({ principal }: { principal: Principal }) {
  const [dialog, setDialog] = useState<"contact" | "password" | "staff" | undefined>();
  const initials = principal.displayName.split(/\s+/).filter(Boolean).slice(0, 2).map(part => part[0]?.toUpperCase()).join("") || "BL";
  const showStaffPreview = ["ROLE-02", "ROLE-06"].includes(principal.roleId);
  return <><div className="profile-identity"><span className="profile-avatar">{initials}</span><div className="profile-identity-copy"><span>Authenticated synthetic participant</span><h2>{principal.displayName}</h2><p className="mono">{principal.userId}</p><div><span className="status">{principal.roleDisplayName}</span><span className="status">{humanizeCode(principal.classification)}</span></div></div><div className="profile-institution"><span>Institution scope</span><strong>{principal.institutionDisplayName}</strong><small>Verified server-assigned scope</small></div></div>
    <div className="profile-preview-layout"><div><section className="profile-preview-section"><header><div><h3>Personal information</h3><p>Mockup-derived contact layout; only safe session identity is available.</p></div><button className="button compact" type="button" onClick={() => setDialog("contact")}>Edit contact</button></header><div className="profile-preview-fields"><PlaceholderField label="Full name" value={principal.displayName}/><PlaceholderField label="Official position"/><PlaceholderField label="Employee reference"/><PlaceholderField label="Institutional email"/><PlaceholderField label="Contact number"/><PlaceholderField label="Professional license"/></div></section>
      <section className="profile-preview-section"><header><div><h3>Facility information</h3><p>Institution details must eventually come from a verified onboarding record.</p></div></header><div className="profile-preview-fields"><PlaceholderField label="Facility name" value={principal.institutionDisplayName}/><PlaceholderField label="Institution reference" value={principal.institutionId}/><PlaceholderField label="Registered legal name"/><PlaceholderField label="Participation type"/><PlaceholderField label="Facility classification"/><PlaceholderField label="Ownership"/><PlaceholderField label="Complete address"/><PlaceholderField label="Official facility contact"/></div></section>
      {showStaffPreview&&<section className="profile-preview-section staff-directory-preview"><header><div><h3>Staff Directory</h3><p>Mockup terminology and PIN-management layout pending approved identity and authorization contracts.</p></div><button className="button compact" type="button" onClick={() => setDialog("staff")}>Manage staff preview</button></header><div className="table-wrap"><table className="data-table"><thead><tr><th>Staff member</th><th>Staff ID</th><th>Classification</th><th>Status</th><th>PIN status</th></tr></thead><tbody><tr><td><strong>Synthetic Head</strong></td><td className="mono">STAFF-SYNTH-01</td><td>Blood Bank Head preview</td><td><span className="status">Active preview</span></td><td><span className="status warning">Not connected</span></td></tr><tr><td><strong>Synthetic Staff</strong></td><td className="mono">STAFF-SYNTH-02</td><td>Blood Bank Staff preview</td><td><span className="status">Active preview</span></td><td><span className="status warning">Not connected</span></td></tr></tbody></table></div><div className="staff-preview-note"><span aria-hidden="true">i</span><p>The official authenticated role remains <b>{principal.roleDisplayName}</b>. “Blood Bank Head” is mockup terminology and does not replace ROLE-02 until the authoritative role model is approved and updated.</p></div></section>}
      <section className="profile-preview-section"><header><div><h3>Licensing and qualification</h3><p>No license or document information is stored by this frontend preview.</p></div></header><div className="profile-preview-fields"><PlaceholderField label="Facility LTO"/><PlaceholderField label="Blood-service license"/><PlaceholderField label="Blood-service category"/><PlaceholderField label="Referral or supplying facility"/></div><div className="profile-document-placeholder"><span aria-hidden="true">≡</span><div><strong>Supporting documents unavailable</strong><p>Document storage, verification, retention, and access controls are not implemented.</p></div></div></section></div>
      <aside><section className="profile-preview-section"><header><div><h3>Credentials and access</h3><p>Safe values returned by the current session.</p></div></header><dl className="profile-kv"><dt>Assigned role</dt><dd>{principal.roleDisplayName}</dd><dt>Role ID</dt><dd className="mono">{principal.roleId}</dd><dt>Institution ID</dt><dd className="mono">{principal.institutionId}</dd><dt>Classification</dt><dd>{humanizeCode(principal.classification)}</dd></dl></section>
      <section className="profile-preview-section"><header><div><h3>Application record</h3><p>Visual parity placeholder.</p></div></header><dl className="profile-kv"><dt>Application ID</dt><dd>Not available</dd><dt>Submitted</dt><dd>Not available</dd><dt>Reviewed</dt><dd>Not available</dd><dt>Application type</dt><dd>Not available</dd></dl></section>
      <section className="profile-preview-section"><header><div><h3>Security</h3><p>Authentication changes require a dedicated secure API.</p></div></header><div className="profile-security-preview"><span aria-hidden="true">◇</span><div><strong>Password</strong><p>Recovery and change workflows are not implemented.</p></div></div><button className="button" type="button" onClick={() => setDialog("password")}>Change password</button></section>
      <div className="profile-preview-note"><span aria-hidden="true">i</span><p>Role and institution cannot be changed from this browser session. Identity, licensing, and application corrections are also unavailable in this visual-only extension.</p></div></aside></div>
    {dialog === "contact" && <PreviewModal title="Edit contact information" description="This dialog is a visual preview and cannot change the authenticated profile." onClose={() => setDialog(undefined)} footer={<><button className="button" type="button" onClick={() => setDialog(undefined)}>Cancel</button><button className="button primary" type="button" disabled>Save changes</button></>}><div className="preview-form-grid"><label>Institutional email<input type="email" placeholder="Not available" disabled/></label><label>Contact number<input placeholder="Synthetic contact preview"/></label></div><p className="preview-modal-note">Name, role, employee reference, email, institution, and licensing corrections require a future reviewed workflow.</p></PreviewModal>}
    {dialog === "password" && <PreviewModal title="Change password" description="No password is read, checked, transmitted, or updated by this visual preview." onClose={() => setDialog(undefined)} footer={<><button className="button" type="button" onClick={() => setDialog(undefined)}>Cancel</button><button className="button primary" type="button" disabled>Update password</button></>}><div className="preview-password-fields"><label>Current password<input type="password" autoComplete="off"/></label><label>New password<input type="password" autoComplete="off"/></label><label>Confirm new password<input type="password" autoComplete="off"/></label></div><p className="preview-modal-note">Password recovery, strength policy, throttling, session revocation, and audit behavior remain unimplemented.</p></PreviewModal>}
    {dialog === "staff" && <PreviewModal title="Protected staff management" description="This dialog reproduces the latest mockup layout without reading, storing, hashing, or verifying a PIN." onClose={() => setDialog(undefined)} footer={<><button className="button" type="button" onClick={() => setDialog(undefined)}>Close</button><button className="button primary" type="button" disabled>Authorize change</button></>}><div className="preview-form-grid"><label>Full name<input value="Synthetic staff preview" disabled/></label><label>Staff ID<input className="mono" value="STAFF-SYNTH-NEW" disabled/></label><label>Classification<select disabled><option>Blood Bank Staff preview</option></select></label><label>Professional license<input value="Not available" disabled/></label><label>Administrative PIN<input type="password" value="" placeholder="Secure API required" disabled/></label><label>PIN enrollment status<input value="Not connected" disabled/></label></div><p className="preview-modal-note">Staff lifecycle, unique operator credentials, administrative authorization, audit attribution, recovery, throttling, and secure PIN storage are not implemented. Duty scheduling is also outside the latest mockup baseline.</p></PreviewModal>}
  </>;
}
