// FR-03–05, FR-09, FR-12–14: retained services, official cookie, real HTTP; no interception.
import {chromium} from '@playwright/test';
import {readFile,writeFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
const base=process.env.BLOODLEDGER_BROWSER_BASE_URL??'http://127.0.0.1:5174';
const config=JSON.parse(await readFile(process.env.BLOODLEDGER_BROWSER_CONFIG_PATH,'utf8'));
const report={classification:'SIMULATION_ONLY',host:process.env.BLOODLEDGER_VALIDATOR_LABEL??'LOCAL_SELF_VALIDATION',interception:false,checks:[]};
const browser=await chromium.launch({headless:true});
try{
 const context=await browser.newContext();const page=await context.newPage();
 assert.equal((await context.request.get(base+'/api/v2/historical-snapshots')).status(),401);
 await page.goto(base+'/inventory');await page.getByLabel('Username').fill(config.accounts.coordinator.username);await page.getByLabel('Password',{exact:true}).fill(config.accounts.coordinator.password);await page.getByRole('button',{name:'Sign in',exact:true}).click();
 await page.getByRole('link',{name:'Inventory',exact:true}).waitFor();assert.ok((await context.cookies()).some(c=>c.name==='bloodledger_session'&&c.httpOnly));
 const endpoints=['dashboard','transfers','alerts','audit','historical-snapshots'];
 for(const endpoint of endpoints){const response=await context.request.get(base+'/api/v2/'+endpoint);assert.equal(response.status(),200,endpoint);const body=await response.json();assert.equal(body.classification,'SIMULATION_ONLY');report.checks.push({endpoint,status:200});}
 const operational=await context.request.get(base+'/api/v2/components',{headers:{'X-BloodLedger-Contract-Version':'V2.1'}});const components=(await operational.json()).components;assert.equal(components.length,9);assert.equal(new Set(components.map(c=>c.componentType)).size,5);assert.equal(components.filter(c=>c.inventoryStatus==='EXPIRED').length,1);
 await page.getByRole('link',{name:'Inventory',exact:true}).click();await page.getByLabel('Contract view').selectOption('V2.1');await page.locator('table tbody tr').nth(8).waitFor();assert.equal(await page.locator('table tbody tr').count(),9);await page.getByRole('button',{name:'Historical synthetic stock',exact:true}).click();await page.getByText('Source: SIM_INSTITUTION_01',{exact:false}).waitFor();assert.equal(await page.locator('table').nth(0).locator('tbody tr').count(),20);assert.equal(await page.locator('table').nth(1).locator('tbody tr').count(),50);await page.getByRole('button',{name:'Next 50 components'}).click();await page.getByRole('button',{name:'First page'}).waitFor();
 const snapshots=await (await context.request.get(base+'/api/v2/historical-snapshots')).json();const snapshot=snapshots.snapshots.find(s=>s.source_business_date.startsWith('2026-10-07'));assert.equal(snapshot.expected_units,522);
 let cursor=null;const ids=new Set();do{const response=await context.request.get(base+'/api/v2/historical-snapshots/'+snapshot.snapshot_id+'?limit=100'+(cursor?'&cursor='+cursor:''));assert.equal(response.status(),200);const detail=await response.json();for(const unit of detail.units){assert.equal(unit.validation_status,'VALID');ids.add(unit.component_id);}cursor=detail.nextCursor;}while(cursor);assert.equal(ids.size,522);
 await page.getByRole('link',{name:'Transfers',exact:true}).click();await page.getByRole('heading',{name:'V2 transfers and reservations'}).waitFor();await page.getByRole('heading',{name:'Start local release',exact:true}).waitFor();await page.locator('table').nth(0).locator('tbody tr').nth(2).waitFor();assert.equal(await page.locator('table').nth(0).locator('tbody tr').count(),3);assert.equal(await page.locator('table').nth(1).locator('tbody tr').count(),2);
 await page.getByRole('link',{name:'Alerts',exact:true}).click();await page.getByText('EXPIRED',{exact:true}).first().waitFor();if(await page.getByRole('button',{name:'Acknowledge',exact:true}).count())await page.getByRole('button',{name:'Acknowledge',exact:true}).click();await page.getByText('Acknowledged',{exact:true}).waitFor();
 await page.getByRole('link',{name:'Audit',exact:true}).click();await page.locator('table tbody tr').first().waitFor();
 await page.getByRole('link',{name:'Analytics',exact:true}).click();const date=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Manila',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());const defaultResponse=await (await context.request.get(base+'/api/v1/demand-forecasts?businessDate='+date)).json();assert.equal(defaultResponse.datasetVersion,'SYNTHETIC_FORECAST_V4_RUNTIME_V1');await page.getByLabel('Business date').fill(date);await page.getByLabel('Forecast version').selectOption('SYNTHETIC_FORECAST_V5_RUNTIME_V1');await page.locator('.forecast-table tbody tr').nth(19).waitFor();assert.equal(await page.locator('.forecast-table tbody tr').count(),20);
 const forecast=await (await context.request.get(base+'/api/v1/demand-forecasts?businessDate='+date+'&datasetVersion=SYNTHETIC_FORECAST_V5_RUNTIME_V1')).json();assert.equal(forecast.forecasts.length,20);report.forecastStatus=forecast.status;report.historicalCount=ids.size;report.operationalCount=components.length;
 // A recipient cannot inspect source-only history or source inventory.
 const recipient=await browser.newContext();await recipient.request.post(base+'/api/v1/auth/session',{headers:{Origin:'http://127.0.0.1:5174'},data:config.accounts.recipient});assert.equal((await recipient.request.get(base+'/api/v2/historical-snapshots')).status(),403);const recipientComponents=await (await recipient.request.get(base+'/api/v2/components',{headers:{'X-BloodLedger-Contract-Version':'V2.1'}})).json();assert.equal(recipientComponents.components.length,0);await recipient.close();
 const csrf=await context.request.post(base+'/api/v2/alerts/V2EXP_COMP_TEST/acknowledge',{headers:{Origin:'https://wrong.invalid'}});assert.equal(csrf.status(),403);
 await context.request.delete(base+'/api/v1/auth/session',{headers:{Origin:'http://127.0.0.1:5174'}});assert.equal((await context.request.get(base+'/api/v2/historical-snapshots')).status(),401);await context.close();report.result='PASS';
}finally{await browser.close();await writeFile(process.env.BLOODLEDGER_BROWSER_REPORT_PATH,JSON.stringify(report,null,2)+'\n',{mode:0o600});}
console.log(JSON.stringify(report));
