import test from 'node:test';
import assert from 'node:assert/strict';
import { seal,unseal,requirePopulationWindow,verificationWindow,allocateLabels,reservationPlan,freezePreview,PREVIEW_SCHEMA,validateScenarioBytes,verifyOperationalCensus } from '../../scripts/development-data/stock-plan.mjs';
import { fingerprintRows } from '../../scripts/development-data/stock-preservation.mjs';
import { digest,id,ledgerCommand,processSavedCommand } from '../../scripts/development-data/scenario.mjs';
import { windowBoundLedger,journalProvenance,assertCommand } from '../../scripts/development-data/stock-cli.mjs';

const time='2026-10-08T08:00:00.000Z';
const scenario={populationNotBefore:time,t0:'2026-10-09T00:00:00.000Z',verificationWindowEndExclusive:'2026-10-09T08:00:00.000Z',units:[
  {unitKey:'UNIT_TRANSFER',donationKey:'DONATION_TRANSFER',reservationKey:'R_TRANSFER',bloodType:'A_POSITIVE',componentType:'WHOLE_BLOOD',issuerInstitutionId:'INST_MEDIATRIX',custodyInstitutionId:'INST_MEDIATRIX',collectedAt:'2026-10-08T00:00:00Z',expiresAt:'2026-10-11T00:00:00Z'},
  {unitKey:'UNIT_LOCAL',donationKey:'DONATION_LOCAL',reservationKey:'R_LOCAL',bloodType:'A_POSITIVE',componentType:'WHOLE_BLOOD',issuerInstitutionId:'INST_MEDIATRIX',custodyInstitutionId:'INST_MEDIATRIX',collectedAt:'2026-10-08T00:00:00Z',expiresAt:'2026-10-11T01:00:00Z'}],reservations:[
  {reservationKey:'R_LOCAL',workflowKey:'W_LOCAL',purpose:'LOCAL_RELEASE',bloodType:'A_POSITIVE',componentType:'WHOLE_BLOOD',quantity:1,sourceInstitutionId:'INST_MEDIATRIX',destinationInstitutionId:null,unitKeys:['UNIT_LOCAL']},
  {reservationKey:'R_TRANSFER',workflowKey:'W_TRANSFER',purpose:'TRANSFER',bloodType:'A_POSITIVE',componentType:'WHOLE_BLOOD',quantity:1,sourceInstitutionId:'INST_MEDIATRIX',destinationInstitutionId:'INST_SYNTH_MEDIX',unitKeys:['UNIT_TRANSFER']} ]};
const labels=()=>allocateLabels(scenario,'1'.repeat(64),1000,Buffer.alloc(32,2));
function preview(){const ls=labels().map(l=>({...l,ocr:{donationNumber:99,bloodType:99,collectedAt:98,expiresAt:98},capturedAt:time,engine:'TESSERACT_JS',engineVersion:'7.0.0'}));const runId=id('STOCK_',`${'1'.repeat(64)}|${digest(scenario)}`);return seal({schemaVersion:PREVIEW_SCHEMA,scenario,runId,labels:ls,reservations:reservationPlan(scenario,ls,[],time,runId),principals:{coordinator:{userId:'USR_TEST',institutionId:'INST_MEDIATRIX'},recipient:{userId:'USR_DEST',institutionId:'INST_SYNTH_MEDIX'}},policyVersion:'SYNTHETIC_INSTITUTION_CORE_V1'});}

test('TP-STOCK-01: exact review hashes fail closed on tampering',()=>{const value=seal({data:1});assert.deepEqual(unseal(value,value.manifestSha256),{data:1});assert.throws(()=>unseal({...value,data:2},value.manifestSha256),/APPROVAL/);assert.throws(()=>validateScenarioBytes(Buffer.from('{}')),/MISMATCH/);});
test('TP-STOCK-01: population and verification have distinct exclusive boundaries',()=>{assert.throws(()=>requirePopulationWindow(scenario,'2026-10-08T07:59:59.999Z'),/CLOSED/);requirePopulationWindow(scenario,time);requirePopulationWindow(scenario,'2026-10-08T23:59:59.999Z');assert.throws(()=>requirePopulationWindow(scenario,scenario.t0),/CLOSED/);assert.throws(()=>requirePopulationWindow(scenario,'invalid'),/CLOSED/);assert.equal(verificationWindow(scenario,scenario.t0),true);assert.equal(verificationWindow(scenario,scenario.verificationWindowEndExclusive),false);});
test('FR-01: backend IDs reproduce uppercase API derivation and singleton grouping',()=>{const ls=labels();assert.equal(ls[0].componentId,id('COMP_',ls[0].idempotencyKey));assert.match(ls[0].donationId,/^DON_[A-F0-9]{40}$/);assert.notEqual(ls[0].donationId,ls[1].donationId);assert.deepEqual(labels(),ls);assert.throws(()=>allocateLabels(scenario,'target',9999,Buffer.alloc(32)),/RANGE/);});
test('BR-INV-03/04: global FEFO orders transfer before local and rejects older stock displacement',()=>{const ls=labels(),plan=reservationPlan(scenario,ls,[],time,'STOCK_TEST');assert.deepEqual(plan.map(r=>r.purpose),['TRANSFER','LOCAL_RELEASE']);assert.equal(plan[1].reservationId,id('RES_',plan[1].idempotencyKey));const old={componentId:'COMP_OLD',inventoryStatus:'AVAILABLE',institutionId:'INST_MEDIATRIX',bloodType:'A_POSITIVE',componentType:'WHOLE_BLOOD',inventoryVersion:1,expiresAt:'2026-10-10T00:00:00.000Z'};assert.throws(()=>reservationPlan(scenario,ls,[old],time,'STOCK_TEST'),/FEFO/);assert.doesNotThrow(()=>reservationPlan(scenario,ls,[{...old,expiresAt:time}],time,'STOCK_TEST'));});
test('BR-INV-04: equal expiry chooses backend ID and rejects a different intended membership',()=>{const ls=labels();const old={...ls[0],componentId:'COMP_0000000000000000000000000000000000000000',inventoryStatus:'AVAILABLE',institutionId:'INST_MEDIATRIX',inventoryVersion:1};assert.throws(()=>reservationPlan(scenario,ls,[old],time,'STOCK_TEST'),/FEFO/);});
test('ADR-035: confirmation freezes actual time, recognized evidence and all commands',()=>{const p=preview(),execution=freezePreview(p,p.manifestSha256,'2026-10-08T08:01:00.000Z');assert.equal(execution.confirmedAt,'2026-10-08T08:01:00.000Z');assert.equal(execution.previewSha256,p.manifestSha256);assert.equal(execution.operations.length,5);assert.ok(execution.operations.every(o=>o.payload.eventTime===execution.confirmedAt&&o.payloadSha256===digest(o.payload)));assert.equal(execution.operations[0].payload.ocrEvidence.fieldConfidence.collectedAt,98);const bad=preview();bad.labels[0].ocr.expiresAt=89;const resealed=seal(Object.fromEntries(Object.entries(bad).filter(([k])=>k!=='manifestSha256')));assert.throws(()=>freezePreview(resealed,resealed.manifestSha256,time),/OCR/);assert.throws(()=>freezePreview(p,p.manifestSha256,'2026-10-08T07:00:00Z'),/CLOSED/);});
test('NFR-02/05: expired window recovers commitment and projection without submitting',async()=>{let submit=0,project=0;const e={transactionId:'tx',validationStatus:'VALID',blockNumber:4};const ledger=windowBoundLedger({inspect:async()=>e,prepare:async()=>{throw Error('unexpected')},submitSaved:async()=>submit++},scenario,()=>new Date(scenario.t0));await processSavedCommand({command:{operation:'SUBMIT_TRANSFER',payload:{},idempotencyKey:'IDEM_TEST'},saved:{transaction_id:'tx',signed_transaction:Buffer.from('signed')},ledger,saveSubmission:async()=>{},saveCommit:async()=>{},project:async()=>project++,complete:async()=>{}});assert.equal(submit,0);assert.equal(project,1);const missing=windowBoundLedger({inspect:async()=>null,submitSaved:async()=>submit++},scenario,()=>new Date(scenario.t0));await assert.rejects(processSavedCommand({command:{operation:'SUBMIT_TRANSFER',payload:{},idempotencyKey:'IDEM_TEST'},saved:{transaction_id:'tx'},ledger:missing,saveCommit:async()=>{},project:async()=>{},complete:async()=>{}}),/WINDOW_CLOSED/);assert.equal(submit,0);});
test('FR-12: durable provenance excludes Donation No. and OCR text while binding requests',()=>{const p=preview(),e=freezePreview(p,p.manifestSha256,time),value=journalProvenance(e);assert.doesNotMatch(JSON.stringify(value),/donationNumber|lookupHmac|capturedAt|"ocr"|"pin"|password/i);assert.ok(value.operations.every(o=>o.payloadSha256));});
test('TP-STOCK-01: preservation excludes only explicitly owned rows, detects old-row mutation',()=>{const old={component_id:'COMP_OLD',status:'AVAILABLE'},own={component_id:'COMP_NEW',status:'RESERVED'};assert.deepEqual(fingerprintRows([old,own],new Set(['COMP_NEW'])),fingerprintRows([old]));assert.notDeepEqual(fingerprintRows([{...old,status:'RESERVED'}]),fingerprintRows([old]));assert.deepEqual(fingerprintRows([{unrelated_id:'COMP_NEW'}],new Set(['COMP_NEW'])),fingerprintRows([{unrelated_id:'COMP_NEW'}]));});
test('FR-03: local-release ledger payload uses canonical ReserveComponents and excludes workflow linkage',()=>{const result=ledgerCommand({operation:'RESERVE_LOCAL_RELEASE',idempotencyKey:'IDEM_TEST',payload:{localReleaseId:'REL_TEST',reservationId:'RES_TEST',purpose:'LOCAL_RELEASE',selectedComponentIds:['COMP_TEST'],expectedComponentVersions:[1],policyVersion:'SYNTHETIC_INSTITUTION_CORE_V1'}});assert.equal(result.operation,'ReserveComponents');assert.equal(result.payload.localReleaseId,undefined);assert.equal(result.payload.reservationId,'RES_TEST');});
test('FR-12: saved command adoption rejects actor and selected-version drift',()=>{const p=preview(),e=freezePreview(p,p.manifestSha256,time),o=e.operations[3],r=e.reservations[0];const command={commandId:o.commandId,idempotencyKey:o.idempotencyKey,actorUserId:'USR_TEST',actorInstitutionId:'INST_MEDIATRIX',correlationId:o.payload.correlationId,operation:'RESERVE_COMPONENTS',payload:{...r,eventTime:e.confirmedAt,actorUserId:'USR_TEST',policyVersion:e.policyVersion,transferId:r.workflowId}};assert.doesNotThrow(()=>assertCommand(command,o,e));assert.throws(()=>assertCommand({...command,actorUserId:'USR_RETIRED'},o,e),/OWNERSHIP/);assert.throws(()=>assertCommand({...command,payload:{...command.payload,expectedComponentVersions:[2]}},o,e),/EVIDENCE/);});
test('FR-09/14: independent forty-series census derives verified zeros and expiry eligibility from accepted stock',()=>{const types=['WHOLE_BLOOD','PACKED_RED_BLOOD_CELLS','FRESH_FROZEN_PLASMA','PLATELETS','CRYOPRECIPITATE'],bloods=['A_POSITIVE','A_NEGATIVE','B_POSITIVE','B_NEGATIVE','AB_POSITIVE','AB_NEGATIVE','O_POSITIVE','O_NEGATIVE'];const snapshot={capturedAt:time,groups:types.map(componentType=>({componentType,bloodTypes:bloods.map(bloodType=>({bloodType,availableCount:0,reservedCount:0,reportableCount:0,forecastEligibleAvailableCount:0}))}))};snapshot.groups[0].bloodTypes[0]={bloodType:'A_POSITIVE',availableCount:2,reservedCount:1,reportableCount:3,forecastEligibleAvailableCount:1};const base={componentType:'WHOLE_BLOOD',bloodType:'A_POSITIVE',expiresAt:'2026-10-09T00:00:00.000Z'};const rows=[{...base,inventoryStatus:'AVAILABLE'},{...base,inventoryStatus:'AVAILABLE',expiresAt:time},{...base,inventoryStatus:'RESERVED'},{...base,inventoryStatus:'IN_TRANSIT'}];assert.doesNotThrow(()=>verifyOperationalCensus(snapshot,rows));const wrong=structuredClone(snapshot);wrong.groups[4].bloodTypes[7].availableCount=1;assert.throws(()=>verifyOperationalCensus(wrong,rows),/COUNTS/);const missing=structuredClone(snapshot);missing.groups[4].bloodTypes.pop();assert.throws(()=>verifyOperationalCensus(missing,rows),/COVERAGE/);const duplicate=structuredClone(snapshot);duplicate.groups[4].bloodTypes[7]=duplicate.groups[4].bloodTypes[6];assert.throws(()=>verifyOperationalCensus(duplicate,rows),/DUPLICATE/);});
