import {useEffect,useRef,useState} from "react";
import type {Principal} from "../../auth/permissions";
import {InformationHelp} from "../../components/ui/information-help";
import {formatBloodType} from "../../components/ui/display";
import {ManualReceiptEntry,type ManualReceiptDraft} from "../receipts/manual-receipt-entry";
import {componentLabel,facilityLabel} from "../transfers/requester-transfer-data";
export type ScannerRequest={source_institution_id?:string;destination_institution_id?:string};
export function BankUnitScanner({principal,requests,onClose}:{principal:Principal;requests:ScannerRequest[];onClose:()=>void}){
 const [direction,setDirection]=useState<"Inbound"|"Outbound">("Inbound");
 const panel=useRef<HTMLElement>(null),close=useRef<HTMLButtonElement>(null);
 useEffect(()=>{const previous=document.activeElement as HTMLElement|null;close.current?.focus();return()=>{if(previous?.isConnected)previous.focus();};},[]);
 function keyDown(event:React.KeyboardEvent){if(event.key==="Escape"){event.preventDefault();onClose();return;}if(event.key!=="Tab")return;const elements=Array.from(panel.current?.querySelectorAll<HTMLElement>('button:not([disabled]),select:not([disabled]),a[href],input:not([hidden]):not([disabled]),iframe')??[]).filter(el=>el.getClientRects().length>0);const first=elements[0],last=elements[elements.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last?.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first?.focus();}}
 return <div className="preview-modal-backdrop receipt-scanner-backdrop bank-scanner-backdrop"><section ref={panel} className="receipt-scanner-dialog bank-scanner-phone" role="dialog" aria-modal="true" aria-label="Mobile blood unit scanner" onKeyDown={keyDown}>
 <header><div><h2>Mobile Blood Unit Scanner</h2><span className="receipt-eyebrow">BloodLedger · {direction}</span></div><button ref={close} className="receipt-close" aria-label="Close mobile scanner" onClick={onClose}>×</button></header>
 <div className="receipt-scanner-content"><div className="receipt-mode-tabs" role="tablist" aria-label="Blood unit direction">{(["Inbound","Outbound"] as const).map(item=><button type="button" role="tab" aria-selected={direction===item} tabIndex={direction===item?0:-1} key={item} onClick={()=>setDirection(item)} onKeyDown={e=>{if(["ArrowLeft","ArrowRight","Home","End"].includes(e.key)){e.preventDefault();const next=e.key==="Home"?"Inbound":e.key==="End"?"Outbound":direction==="Inbound"?"Outbound":"Inbound";setDirection(next);e.currentTarget.parentElement?.querySelectorAll<HTMLButtonElement>('button')[next==="Inbound"?0:1]?.focus();}}}>{item}</button>)}</div>
 <BankScannerInput key={direction} direction={direction} principal={principal} requests={requests}/></div></section></div>;
}
function BankScannerInput({direction,principal,requests}:{direction:"Inbound"|"Outbound";principal:Principal;requests:ScannerRequest[]}){
 const [mode,setMode]=useState<"Scan"|"Manual">("Scan"),[draft,setDraft]=useState<ManualReceiptDraft>(),[imageUrl,setImageUrl]=useState<string>(),[imageError,setImageError]=useState("");
 const chooser=useRef<HTMLInputElement>(null),capture=useRef<HTMLIFrameElement>(null);const [captureHeight,setCaptureHeight]=useState(650);
 useEffect(()=>()=>{if(imageUrl)URL.revokeObjectURL(imageUrl);},[imageUrl]);
 useEffect(()=>{const resize=(event:MessageEvent)=>{if(event.origin!==location.origin||event.source!==capture.current?.contentWindow||event.data?.type!=="bloodledger:capture-height")return;const height=Number(event.data.height);if(Number.isFinite(height))setCaptureHeight(Math.min(5000,Math.max(280,height)));};addEventListener("message",resize);return()=>removeEventListener("message",resize);},[]);
 const facilities=[...new Set(requests.map(row=>direction==="Inbound"?row.source_institution_id:row.destination_institution_id).filter((id):id is string=>Boolean(id)&&id!==principal.institutionId))];
 function imageChanged(file?:File){setImageUrl(undefined);setImageError("");if(!file)return;if(!["image/jpeg","image/png"].includes(file.type)||file.size>10*1024*1024){setImageError("Choose a JPG or PNG image up to 10 MB.");return;}setImageUrl(URL.createObjectURL(file));}
 return <><section className="receipt-input-card"><header><h3>{direction} Blood Unit Input</h3><InformationHelp label={direction+" blood unit input"}>{direction==="Inbound"?"Scan an approved label, run OCR, review the extracted fields, and authorize intake through the verified capture workflow. Manual entries are a local preview only.":"Capture an outgoing label or enter unit details to preview them. Outbound scan matching is not connected. Use Requests & Transfers for the supported dispatch workflow."}</InformationHelp></header>
 <div className="receipt-mode-tabs" role="tablist" aria-label="Blood unit input method">{(["Scan","Manual"] as const).map(item=><button type="button" role="tab" key={item} aria-selected={mode===item} aria-controls="bank-unit-input-panel" tabIndex={mode===item?0:-1} id={"bank-input-"+item} onClick={()=>setMode(item)} onKeyDown={e=>{if(["ArrowLeft","ArrowRight","Home","End"].includes(e.key)){e.preventDefault();const next=e.key==="Home"?"Scan":e.key==="End"?"Manual":mode==="Scan"?"Manual":"Scan";setMode(next);document.getElementById("bank-input-"+next)?.focus();}}}>{item}</button>)}</div>
 <div id="bank-unit-input-panel" role="tabpanel" aria-labelledby={"bank-input-"+mode}>
 {direction==="Inbound"&&<div hidden={mode!=="Scan"}><iframe ref={capture} src="/capture/?layout=receipt" title="BloodLedger mobile capture workspace" allow="camera" className="bank-receipt-capture" style={{height:captureHeight}}/></div>}
 {direction==="Outbound"&&mode==="Scan"&&<><div className="receipt-camera-stage">{imageUrl?<img src={imageUrl} alt="Selected outbound label preview"/>:<><svg width="42" height="42" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.3" aria-hidden="true"><path d="M3 7h4l2-3h6l2 3h4v13H3Z"/><circle cx="12" cy="13" r="4"/></svg><strong>Capture a blood-unit label</strong><span>Use your phone camera or choose an image.</span></>}<span className="receipt-camera-corners" aria-hidden="true"/></div><input ref={chooser} type="file" accept="image/jpeg,image/png" capture="environment" hidden aria-label="Outbound blood-unit label image" onChange={e=>{imageChanged(e.target.files?.[0]);e.target.value="";}}/><div className="receipt-capture-actions"><button className="button primary compact" onClick={()=>chooser.current?.click()}>{imageUrl?"Replace image":"Take photo / Choose image"}</button>{imageUrl&&<button className="button compact" onClick={()=>setImageUrl(undefined)}>Clear image</button>}</div>{imageError&&<p className="receipt-image-error" role="alert">{imageError}</p>}<p className="receipt-preview-note">Photo preview only. Outbound label matching is not connected yet.</p></>}
 <div hidden={mode!=="Manual"}><ManualReceiptEntry incoming={[]} principal={principal} initial={draft} onPreview={setDraft} facilityOptions={facilities} facilityFieldLabel={direction==="Inbound"?"Source Facility":"Destination Facility"} purposePlaceholder={direction==="Inbound"?"e.g. Blood unit intake":"e.g. Blood unit dispatch"}/></div>
 </div></section>
 {(mode==="Manual"||direction==="Outbound")&&<section className="receipt-review-card"><header><h3>{draft?direction+" Preview":"Awaiting Input"}</h3><InformationHelp label="Blood unit verification">Local photos and manually entered details do not register inventory or dispatch units. The appropriate verified transaction must be connected before confirmation is enabled.</InformationHelp></header>{draft?<><p className="receipt-preview-note">Manual entry preview · Not verified</p><dl>{Object.entries({"Unit ID":draft.unitId,"Blood type":formatBloodType(draft.bloodType),"Component":componentLabel(draft.component),"Collection date":draft.collected||"Not entered","Expiration date":draft.expires,"Facility":draft.facility?facilityLabel(draft.facility,principal):"Not entered","Purpose":draft.purpose||"Not entered"}).map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl></>:<div className="requester-records-empty"><strong>Scan a label or enter unit details</strong><span>Your entry preview will appear here.</span></div>}<div className="receipt-confirm-footer"><button className="button primary compact" disabled title="Verified transaction matching is not connected.">Confirm {direction.toLowerCase()} transaction</button><span>{direction==="Outbound"?"Outbound scan matching is not connected yet.":"Manual intake is not connected yet."}</span>{direction==="Outbound"&&<a className="button compact" href="/transfers">Open Requests &amp; Transfers</a>}</div></section>}
 </>;
}
