import { BankUnitScanner, type ScannerRequest } from "./bank-unit-scanner";
import {useState} from "react";
import {can,canAct,type Principal} from "../../auth/permissions";
import {ActionIcon} from "../../components/ui/action-icon";
import {InformationHelp} from "../../components/ui/information-help";
import {RefreshButton} from "../../components/ui/refresh-button";
import {formatManilaDateTime,humanizeCode,statusClassName} from "../../components/ui/display";
import {useLiveData} from "../../hooks/use-live-data";
import type {Audit} from "../../services/api/types";
import {exportTablePdf} from "../../services/pdf/table-report";
type Operation={command_id:string;resource_id:string;operation:string;status:string;accepted_at:string;ledger_transaction_id:string|null};
type Transaction={id:string;time:string;direction:string;reference:string;unit:string|null;operation:string;status:string;ledger:string|null};
const direction=(action:string)=>/REGISTER_INBOUND|RECEIVE_/.test(action)?"Inbound":/DISPATCH_|COMPLETE_LOCAL_RELEASE/.test(action)?"Outbound":null;
export function BloodUnitTransactionsPage({principal}:{principal:Principal}){
 const activity=useLiveData<Audit>(can(principal,"audit:read")?"/api/v2/audit":null);
 const commands=useLiveData<{timeline:Operation[];requests?:ScannerRequest[];classification:string}>(can(principal,"transfers:read")?"/api/v2/transfers":null);
 const [scannerOpen,setScannerOpen]=useState(false);
 const [filter,setFilter]=useState("ALL"),[search,setSearch]=useState(""),[exporting,setExporting]=useState(false),[message,setMessage]=useState("");
 const scopedAudit=activity.data?.classification==="SIMULATION_ONLY"&&activity.data.scope==="INSTITUTION"?activity.data.events:undefined;
 const timeline=commands.data?.classification==="SIMULATION_ONLY"?commands.data.timeline:undefined;
 const rows:Transaction[]=(timeline??[]).filter(row=>direction(row.operation)).map(row=>({id:row.command_id,time:row.accepted_at,direction:direction(row.operation)!,reference:row.resource_id,unit:row.resource_id.startsWith("COMP_")?row.resource_id:null,operation:row.operation,status:row.status,ledger:row.ledger_transaction_id}));
 const ledgerRefs=new Set(rows.map(row=>row.ledger).filter(Boolean));
 for(const event of scopedAudit??[])if(direction(event.actionCode)&&(!event.ledgerTransactionId||!ledgerRefs.has(event.ledgerTransactionId)))rows.push({id:event.auditEventId,time:event.eventTime,direction:direction(event.actionCode)!,reference:event.correlationId,unit:null,operation:event.actionCode,status:event.outcome,ledger:event.ledgerTransactionId});
 rows.sort((a,b)=>Date.parse(b.time)-Date.parse(a.time));
 const visible=rows.filter(row=>(filter==="ALL"||row.direction===filter)&&[row.reference,row.unit??"",row.operation,row.status,row.ledger??""].some(value=>value.toLowerCase().includes(search.trim().toLowerCase())));
 const loaded=Boolean(scopedAudit||timeline),busy=activity.busy||commands.busy,error=activity.error||commands.error;
 const mayCapture=principal.accountId?canAct(principal,"inventory:capture"):["ROLE-01","ROLE-02"].includes(principal.roleId)&&principal.institutionId==="INST_MEDIATRIX";
 const refresh=()=>{activity.manual();commands.manual();};
 async function exportPdf(){setExporting(true);setMessage("");try{await exportTablePdf({title:"Blood Unit Transactions",scope:principal.institutionDisplayName,filters:`Direction: ${filter}; Search: ${search||"None"}`,headers:["Recorded time","Direction","Record reference","Unit ID","Activity","Status","Ledger reference"],rows:visible.map(row=>[formatManilaDateTime(row.time),row.direction,row.reference,row.unit,humanizeCode(row.operation),humanizeCode(row.status),row.ledger]),filename:"blood-unit-transactions"});}catch(reason){setMessage(reason instanceof Error?reason.message:"PDF export failed.");}finally{setExporting(false);}}
 return <div className="page blood-unit-transactions-page"><header className="page-head"><h1 className="page-title">Blood Unit Transactions</h1><div className="bank-toolbar-actions"><button className="button compact" disabled={!visible.length||exporting} onClick={()=>void exportPdf()}><ActionIcon kind="download"/>{exporting?"Exporting…":"Export PDF"}</button><a className="button compact" href="/inventory">View Inventory</a><RefreshButton busy={busy} onRefresh={refresh}/></div></header>
 <section className="receipt-launch-card"><div className="receipt-launch-icon" aria-hidden="true"><svg width="28" height="28" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.4"><path d="M3 7h4l2-3h6l2 3h4v13H3Z"/><circle cx="12" cy="13" r="4"/></svg></div><div className="receipt-launch-copy"><span className="receipt-eyebrow">Mobile workflow</span><h2>Scan blood units from a phone</h2><p>Scan incoming units or preview outgoing units in the mobile scanner.</p></div>{mayCapture?<button className="button primary compact" onClick={()=>setScannerOpen(true)}>Open Mobile Scanner</button>:<button className="button primary compact" disabled>Open Mobile Scanner</button>}<InformationHelp label="Mobile scanner">The receipt-style phone supports verified inbound OCR intake and local outbound/manual previews. Outbound scan matching and manual transaction submission are not connected yet. Use Requests & Transfers for supported dispatch. Your operator must have capture permission.</InformationHelp></section>
 {error&&<div className="requester-transfer-notice" role="status"><div className="requester-notice-copy"><strong>Some transaction records could not refresh</strong><p>{error}</p></div><button className="button compact" onClick={refresh}>Retry</button></div>}{message&&<p role="status">{message}</p>}
 <section className="bank-record-card receipt-history-card"><header className="bank-section-heading"><h2>Recent Blood Unit Transactions</h2><InformationHelp label="Recent Blood Unit Transactions">Review permitted inbound registration, receipt, dispatch and local-release records. A row’s status identifies its recorded outcome; pending commands are not ledger commitments. Scan IDs, unit details and method are unavailable unless the read service supplies them. PDF exports contain this filtered snapshot only.</InformationHelp></header><div className="bank-list-filters"><label className="bank-search">Search transactions<input type="search" value={search} placeholder="Reference, activity or status…" onChange={event=>setSearch(event.target.value)}/></label><label>Direction<span className="requester-select"><select aria-label="Direction" value={filter} onChange={event=>setFilter(event.target.value)}><option value="ALL">All directions</option><option>Inbound</option><option>Outbound</option></select></span></label></div>
 {!loaded?<div className="requester-records-empty"><strong>{error?"Transaction history unavailable":"Loading transaction records…"}</strong></div>:!visible.length?<div className="requester-records-empty"><strong>{rows.length?"No transactions match your filters":"No blood-unit transactions recorded"}</strong><span>Permitted recorded activity will appear here.</span></div>:<div className="table-wrap"><table className="data-table transaction-history-table"><thead><tr><th>Time</th><th>Type</th><th>Record reference</th><th>Unit ID</th><th>Activity</th><th>Status</th><th>Ledger reference</th></tr></thead><tbody>{visible.map(row=><tr key={row.id}><td>{formatManilaDateTime(row.time)}</td><td>{row.direction}</td><td className="mono">{row.reference}</td><td className="mono">{row.unit??"Not available"}</td><td>{humanizeCode(row.operation)}</td><td><span className={statusClassName(row.status)}>{humanizeCode(row.status)}</span></td><td className="mono">{row.ledger??"No ledger reference"}</td></tr>)}</tbody></table></div>}
 </section>{scannerOpen&&<BankUnitScanner principal={principal} requests={commands.data?.classification==="SIMULATION_ONLY"?commands.data.requests??[]:[]} onClose={()=>setScannerOpen(false)}/>}</div>;
}
