import type { Pool } from "pg";
import type { ApplicationReadRepository, InventoryAggregateView, InventoryStatus, InventoryUnitView, PendingScanCount } from "./application-read.js";
const iso=(value:unknown)=>value instanceof Date?value.toISOString():new Date(String(value)).toISOString();
export class PostgresApplicationReadRepository implements ApplicationReadRepository {
  constructor(private readonly pool:Pool){}
  async listInventoryUnits(institutionId:string):Promise<InventoryUnitView[]>{const result=await this.pool.query(`SELECT unit_id,institution_id,blood_type,component,collected_at,expires_at,inventory_status,ledger_version,ledger_transaction_id,projected_at FROM app.inventory_projection WHERE institution_id=$1 ORDER BY expires_at,unit_id`,[institutionId]);return result.rows.map(row=>({unitId:String(row.unit_id),institutionId:String(row.institution_id),bloodType:String(row.blood_type),component:String(row.component),collectedAt:iso(row.collected_at),expiresAt:iso(row.expires_at),inventoryStatus:String(row.inventory_status) as InventoryStatus,ledgerVersion:Number(row.ledger_version),ledgerTransactionId:String(row.ledger_transaction_id),projectedAt:iso(row.projected_at),classification:"SIMULATION_ONLY"}))}
  async listInventoryAggregates(institutionId?:string):Promise<InventoryAggregateView[]>{const values:unknown[]=[];const scope=institutionId?"AND p.institution_id=$1":"";if(institutionId)values.push(institutionId);const result=await this.pool.query(`SELECT p.institution_id,i.display_name AS institution_display_name,p.blood_type,p.component,p.inventory_status,count(*)::integer AS confirmed_count,max(p.projected_at) AS last_projected_at FROM app.inventory_projection p JOIN app.institutions i ON i.institution_id=p.institution_id WHERE i.status='ACTIVE' ${scope} GROUP BY p.institution_id,i.display_name,p.blood_type,p.component,p.inventory_status ORDER BY i.display_name,p.blood_type,p.component,p.inventory_status`,values);return result.rows.map(row=>({institutionId:String(row.institution_id),institutionDisplayName:String(row.institution_display_name),bloodType:String(row.blood_type),component:String(row.component),inventoryStatus:String(row.inventory_status) as InventoryStatus,confirmedCount:Number(row.confirmed_count),lastProjectedAt:iso(row.last_projected_at)}))}
  async listPendingScans(institutionId?:string):Promise<PendingScanCount[]>{const values:unknown[]=[];const scope=institutionId?"WHERE institution_id=$1 AND status <> 'COMMITTED'":"WHERE status <> 'COMMITTED'";if(institutionId)values.push(institutionId);const result=await this.pool.query(`SELECT status,count(*)::integer AS count FROM app.scan_events ${scope} GROUP BY status ORDER BY status`,values);return result.rows.map(row=>({status:String(row.status),count:Number(row.count)}))}
}
